### PR TITLE
Move HumanStatus to Presenter

### PR DESCRIPTION
**Pull request by phecho**
I think the most suitable place of HumanStatus is to stay Presenter.

### CODE REVIEW

**Comment by phecho** [comment]
Can you get in and talk about my changes?
@GrahamCampbell @jbrooksuk

**Comment by jbrooksuk** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
Very good. :+1:

**Comment by phecho** [comment]
It seems like this is a good change. I'll change the other place after the completion of this PR.

**Comment by GrahamCampbell** [comment]
Sorry travis is so slow.

**Comment by GrahamCampbell** [comment]
:snowman:

**Comment by jbrooksuk** [comment]
:santa:

**Comment by phecho** [comment]
:christmas_tree:

**Pull request merged**
