### PR TITLE
Fix component group status calculation when components are ordered

### PR DESCRIPTION
**Pull request by nicolasfagotti**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
A better thing to do would be to remove the order by from the base components method, and get other callees to apply the ordering, or define another ordered relation method for components, and get callees to use that.

**Comment by jbrooksuk** [comment]
In agreement with @GrahamCampbell :)

**Comment by jbrooksuk** [comment]
@nicolasfagotti are you able to make the suggested changes?

**Comment by nicolasfagotti** [comment]
Sure. Will try to push the change today :)

**Comment by willallen** [comment]
Hey guys - will this be included in 2.4?

**Comment by nicolasfagotti** [comment]
@willallen, the bug has been fixed for 2.4. This branch has not been merged because the Cachet guys did a much better job implementing GrahamCampbell suggestion.

**Comment by jbrooksuk** [comment]
Thanks @nicolasfagotti :)

**Pull request closed without merging**
