### PR TITLE
Deal with 401 exceptions in a better way

### PR DESCRIPTION
**Pull request by GrahamCampbell**
I've not tested this. I hope it works. :P

### CODE REVIEW

**Comment by TheoBearman** [comment]
@GrahamCampbell I'll be the guinea pig!

**Comment by GrahamCampbell** [comment]
:)

**Comment by jbrooksuk** [comment]
Derp fix, fixes it :+1:

**Comment by GrahamCampbell** [comment]
:ship:

**Comment by GrahamCampbell** [comment]
I guess we should probably add a unit test for this.

**Comment by jbrooksuk** [comment]
:smile:

**Comment by TheoBearman** [comment]
Fix is working for me.

**Comment by GrahamCampbell** [comment]
Yey. :)

**Comment by TheoBearman** [comment]
@GrahamCampbell Thanks for getting a fix out so quickly. Looking forward to tomorrow night @jbrooksuk!

**Comment by jbrooksuk** [comment]
There likely won't be many further changes tbh.

**Comment by TheoBearman** [comment]
Still an amazing achievement/milestone to get an official release out.

**Comment by jbrooksuk** [comment]
Indeed it is! :)

**Pull request merged**
