### PR TITLE
Wip: dockerize

### PR DESCRIPTION
**Pull request by erfantkerfan**
#4404

### CODE REVIEW

**Comment by erfantkerfan** [comment]
I will also add the automated build steps after each release an github actions if we solve the existing issues with the v3 code.

**Comment by jbrooksuk** [comment]
Thanks for this, but we have a separate repo for docker; [cachethq/docker](https://github.com/cachethq/docker).

**Comment by erfantkerfan** [comment]
The mentioned repo was last committed in 4 years ago so I took the guess that its abandoned.
You want me to switch this over to that repo?

**Comment by jbrooksuk** [comment]
There is a PR in progress for this, https://github.com/cachethq/Docker/pull/429

Would love someone to help me automate this and basically just own this for now.

**Comment by jbrooksuk** [comment]
Especially for the 2.4 and 3.x branches of Cachet.

**Pull request closed without merging**
