### PR TITLE
Native throttling

### LINKED ISSUE #1315: Switch away from Laravel-Throttle in favour of native laravel implementation
https://github.com/illuminate/cache/blob/5.2/RateLimiter.php

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Closes #1315.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Is their middleware actually the same.

**Comment by GrahamCampbell** [comment]
I was only really suggesting we used their rate limiter, and did our own middleware.

**Comment by GrahamCampbell** [comment]
Maybe we need to hold off a bit more before switching because I'm already aware of a few unsolved bugs in laravel's throttle stuff.

**Comment by jbrooksuk** [comment]
Ok, I'll move the issue to 2.2.0 then :)

**Comment by GrahamCampbell** [comment]
Sure. ;)

**Comment by jbrooksuk** [comment]
I'm pretty sure this is good to go?

**Comment by GrahamCampbell** [comment]
I'll look at this later this week. ;)

**Pull request merged**
