### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Ping @jbrooksuk or @joecohens. Tests failing. Likely related to something I broke in auto-presenter?

**Comment by jbrooksuk** [comment]
Possible. We decorate the API output, so we'll have to see if that's changed in any way.

**Comment by jbrooksuk** [comment]
Lol what?

```
1) CachetHQ\Tests\Cachet\Api\ComponentTest::testGetComponents
Unable to find JSON fragment ["id":1] within [{"data":[[],[],[]],"meta":{"pagination":{"count":3,"current_page":1,"links":{"next_page":null,"previous_page":null},"per_page":20,"total":3,"total_pages":1}}}].
Failed asserting that false is true.
/home/travis/build/cachethq/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Testing/CrawlerTrait.php:733
/home/travis/build/cachethq/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Testing/CrawlerTrait.php:698
/home/travis/build/cachethq/Cachet/tests/Api/ComponentTest.php:26
2) CachetHQ\Tests\Cachet\Api\IncidentTest::testGetIncidents
Unable to find JSON fragment ["id":1] within [{"data":[[],[],[]],"meta":{"pagination":{"count":3,"current_page":1,"links":{"next_page":null,"previous_page":null},"per_page":20,"total":3,"total_pages":1}}}].
Failed asserting that false is true.
/home/travis/build/cachethq/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Testing/CrawlerTrait.php:733
/home/travis/build/cachethq/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Testing/CrawlerTrait.php:698
/home/travis/build/cachethq/Cachet/tests/Api/IncidentTest.php:26
3) CachetHQ\Tests\Cachet\Api\MetricTest::testGetMetrics
Unable to find JSON fragment ["id":1] within [{"data":[[],[],[]],"meta":{"pagination":{"count":3,"current_page":1,"links":{"next_page":null,"previous_page":null},"per_page":20,"total":3,"total_pages":1}}}].
Failed asserting that false is true.
/home/travis/build/cachethq/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Testing/CrawlerTrait.php:733
/home/travis/build/cachethq/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Testing/CrawlerTrait.php:698
/home/travis/build/cachethq/Cachet/tests/Api/MetricTest.php:26
```

**Comment by GrahamCampbell** [comment]
> Lol what?

Yeh. That's what I was saying. Something's fucked up here.

**Comment by GrahamCampbell** [comment]
I'll make a new PR without the autopresenter changes.

**Comment by GrahamCampbell** [comment]
Infact, I'll just update this PR.

**Comment by GrahamCampbell** [comment]
Passing without the autopresenter update/

**Pull request merged**
