### PR TITLE
Finally fixed the Gulp build process

### PR DESCRIPTION
**Pull request by jbrooksuk**
Right, this **absolutely** fixes the gulp build on my machine. I've ran `gulp` about 100 times now and not once has it kicked off about a missing file.

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Also, I've added an elixir compatible jshint check.

**Comment by GrahamCampbell** [comment]
Does minification of the js work?

**Comment by GrahamCampbell** [comment]
That would be very useful.

**Comment by jbrooksuk** [comment]
Not yet, I'll do that now :)

**Comment by GrahamCampbell** [comment]
That would fix github thinking this isn't a php repo too.

**Comment by jbrooksuk** [comment]
I think the only way is to run `gulp --production`. Unless we look at Elixir...

**Comment by GrahamCampbell** [comment]
That's probably fine then. Just make sure we always do that.

**Comment by jbrooksuk** [comment]
I have an idea.

**Comment by jbrooksuk** [comment]
Nailed it. Push incoming.

**Comment by jbrooksuk** [comment]
Done.

**Pull request merged**
