### PR TITLE
Create ISSUE_TEMPLATE

### PR DESCRIPTION
**Pull request by jbrooksuk**
I'm going to give this new GitHub feature a go :)

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
We should say that they should be running the latest version of cachet too.

**Comment by jbrooksuk** [comment]
> You're running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.

**Comment by GrahamCampbell** [comment]
This also needs adding to the export ignore file.

**Comment by jbrooksuk** [comment]
The what?

**Comment by lenovouser** [comment]
This won't work because you set the `2.1` branch as default on GitHub :smile:

**Comment by jbrooksuk** [comment]
Yeah, that's fine :) We usually switch back to `master` after the release.

**Comment by GrahamCampbell** [comment]
Yeh, the master might become the default today after we do 2.1.2.

**Comment by jbrooksuk** [comment]
Once it's done, I'll upgrade.

**Comment by lenovouser** [comment]
Ah, okay. Cool.

**Comment by lenovouser** [comment]
You guys are ~~f*****g~~ fast in responding tbh :smile: :+1:

**Comment by jbrooksuk** [comment]
:smile:

**Pull request merged**
