### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by TheoBearman** [comment]
This is a new one:

image

**Comment by GrahamCampbell** [comment]
Well, that can't have come from this commit?

**Comment by TheoBearman** [comment]
I didn't know where it came from so I thought it was best to put it here. Shall I open a new issue?

**Comment by GrahamCampbell** [comment]
What version of php do you have?

**Comment by GrahamCampbell** [comment]
I can't replicate this on php 7.0.x?

**Comment by GrahamCampbell** [comment]
Try running `composer self-update`.

**Comment by GrahamCampbell** [comment]
And `composer clear-cache`, and `rm -rf vendor`, then try again.

**Comment by TheoBearman** [comment]
All good.

**Pull request merged**
