### PR TITLE
Upgraded to laravel 5.1

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Did I miss anything regarding the fact that apc is not longer a required cache driver?

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Sweet! This closes #600 too!

**Comment by GrahamCampbell** [comment]
StyleCI broken again. I have no idea what's causing that?

**Comment by jbrooksuk** [comment]
Moondragon!

**Comment by GrahamCampbell** [comment]
lol - doubt it's related

**Comment by GrahamCampbell** [comment]
StyleCI seems to be working again?

**Comment by joecohens** [comment]
Cool :+1: !!!

**Comment by GrahamCampbell** [comment]
@joecohens Looking more closely, StyleCI is still broken. It's been randomly not updating the status of commits for weeks. I have no idea why.

**Comment by GrahamCampbell** [comment]
Is this PR good to merge?

**Comment by joecohens** [comment]
@GrahamCampbell Since the update to 5.1? Maybe?

**Comment by GrahamCampbell** [comment]
> Since the update to 5.1? Maybe?

Been failing all month I think.

**Comment by GrahamCampbell** [comment]
Look through https://github.com/cachethq/Cachet/compare/v0.1.0-alpha...master. Starts happening on May 10th.

**Comment by joecohens** [comment]
> Is this PR good to merge?
Yeah it is :)

**Comment by GrahamCampbell** [comment]
No commits were pushed to StyleCI on May 10th. Some were on May 9th though.

Could this introduce the changes that's causing these failures?
https://github.com/StyleCI/StyleCI/commit/8f801d787547c28deb02dc126796ea7fa362c1bc

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/compare/v5.0.28...5.0.30

**Comment by joecohens** [comment]
Maybe, I can make a quick test locally with the latest changes

**Pull request merged**
