### PR TITLE
Fixed the german translation

### PR DESCRIPTION
**Pull request by karaktaka**
I updated the German translation. No more mixing of formal and personal salutation and some other grammatically errors and typos.

### CODE REVIEW

**Comment by ConnorVG** [comment]
Do we want to drop formality? (ie: "Du hast" -> "Sie haben")

**Comment by karaktaka** [comment]
It was already mixed up. Sometimes "Sie" sometimes "Du". I could change it back to "Du", but i think you don't want to mix both salutations

**Comment by ConnorVG** [comment]
It might be wise we pick one and stick with it, sure. Could you possibly contribute these to the [translation project](https://translate.cachethq.io/project/cachet)?

**Comment by karaktaka** [comment]
Looks like it would take ages to check for typos there, but I'll try to contribute there. ;)

**Comment by ConnorVG** [comment]
Thanks, we really appreciate it :smile:

**Pull request closed without merging**
