### PR TITLE
Components can now be re-ordered, closes #165

### LINKED ISSUE #165: Re-order components
It may be useful to be able to re-order the components. It's not a major feature or anything, but it's just one of those subtleties which would make Cachet feel more complete.

### PR DESCRIPTION
**Pull request by jbrooksuk**
Nice and easy re-ordering using [Sortable](https://rubaxa.github.io/Sortable/).

screenshot 2015-01-01 13 38 07

Using `.ion-drag` for a handle.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Shall I apply this diff? https://styleci.grahamjcampbell.co.uk/commits/6ab16f98ab2b09960270135ef20823b308037e20/diff

**Comment by jbrooksuk** [comment]
I've just pushed a few. If you can apply the rest, please do :)

**Comment by GrahamCampbell** [comment]
You know the point in that diff is that you can automatically apply it with git. :)

**Comment by jbrooksuk** [comment]
Heh, yeah, I keep meaning to just apply the diff. I use the CLI/Sublime Git so I need to learn the commands.

**Comment by GrahamCampbell** [comment]
I'll apply it...

**Comment by jbrooksuk** [comment]
I now know how to apply the diff via command line :)

Thanks!

**Comment by GrahamCampbell** [comment]
Oh, yeh, also in all the migration files, we should always be importing `Illuminate\Support\Facades\Schema`. Just something for the future when `Schema` is removed from the aliases list.

**Comment by jbrooksuk** [comment]
Ok, cool :)

**Pull request merged**
