### PR TITLE
Last hour of metric points

### LINKED ISSUE #1227: More realtime metric graphs
How easy would it be to have a last hour metric graph? This would be great for real time monitoring.

### PR DESCRIPTION
**Pull request by jbrooksuk**
Needs testing on SQLite and PgSQL.

---

Closes #1227.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Just deploy it to the demo website. ;P

**Comment by GrahamCampbell** [comment]
We're running postgres on there.

**Comment by jbrooksuk** [comment]
Will do :trollface:

**Comment by GrahamCampbell** [comment]
let's just assume this works for now

**Pull request merged**
