### PR TITLE
add cron config

### PR DESCRIPTION
**Pull request by n0mer**
for #852

### CODE REVIEW

**Comment by jbrooksuk** [comment]
:+1:

**Comment by n0mer** [comment]
@jbrooksuk , https://registry.hub.docker.com/u/cachethq/cachet/ - this build is from `master` or `1.1` branch?

**Comment by GrahamCampbell** [comment]
Nobody should be using the master branch ever.

**Comment by GrahamCampbell** [comment]
Indeed 1.1 either. We only recommend you use our tagged releases.

**Comment by n0mer** [comment]
This picture says the opposite:

image

**Pull request merged**
