### PR TITLE
[WIP] Started work on Middleware tests

### PR DESCRIPTION
**Pull request by jbrooksuk**
@GrahamCampbell would you suggest testing like this, or by mocking a request to `handle`?

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
No way we should be unit testing middlewares.

**Comment by GrahamCampbell** [comment]
In terms of mocking a request, just litterally make an internal request?

**Comment by jbrooksuk** [comment]
> In terms of mocking a request, just litterally make an internal request?

Yeah.

**Comment by jbrooksuk** [comment]
Want to close this then @GrahamCampbell?

**Pull request closed without merging**
