### PR TITLE
add metric query changes to fix exception

### PR DESCRIPTION
**Pull request by viraja1**
Fixes the following issues:-
https://github.com/CachetHQ/Cachet/issues/3254
https://github.com/CachetHQ/Cachet/issues/3444

### CODE REVIEW

**Comment by Fireant456** [comment]
Can we get this pushed, I would really like to not have to build cachet docker myself to fix issues with metrics graphs

**Comment by Fireant456** [comment]
https://hub.docker.com/repository/docker/fireant456/cachet If anyone needs it temporarily

**Comment by jbrooksuk** [comment]
Can you fix the conflicts and then I'll merge this :)

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.

**Pull request closed without merging**
