### PR TITLE
Move the CONTRIBUTING.md file into .github

### PR DESCRIPTION
**Pull request by jbrooksuk**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Why would we want to do this?

**Comment by jbrooksuk** [comment]
Because that's where it belongs now.

**Comment by GrahamCampbell** [comment]
It doesn't have to go there. Why would we want to make it hard to find? We wouldn;'t move the readme, so why move that file?

**Comment by jbrooksuk** [comment]
Revert then :)

**Pull request merged**
