### PR TITLE
Skip code coverage on pull request builds

### LINKED ISSUE #1261: Don't generate code coverage on pull request builds
It just takes ages, then gets discarded at the end...

### PR DESCRIPTION
**Pull request by GrahamCampbell**
No idea if this will work, lol.

---

Closes #1261.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Closes #1261.

**Comment by jbrooksuk** [comment]
Sweet!

**Comment by GrahamCampbell** [comment]
image

LOL. I have no idea what I'm doing. James - do you know wtf syntax we're meant to use here?

**Comment by jbrooksuk** [comment]
Lol! I'm not sure, but I'll have a look.

**Comment by jbrooksuk** [comment]
Do parenthesis even work in bash?

**Comment by GrahamCampbell** [comment]
Well we're fucked if they don't, lol.

**Comment by jbrooksuk** [comment]
http://stackoverflow.com/questions/2188199/how-to-use-double-or-single-bracket-parentheses-curly-braces

**Comment by GrahamCampbell** [comment]
None of those examples deal with nested logical statements though.

**Comment by jbrooksuk** [comment]
http://www.unix.com/shell-programming-and-scripting/175348-nested-logical-expression-bash-shell.html

Looks right to me.

**Comment by GrahamCampbell** [comment]
Hmmm.

**Comment by GrahamCampbell** [comment]
Fuck it.

**Pull request closed without merging**
