### PR TITLE
[WIP] New design

### PR DESCRIPTION
**Pull request by jbrooksuk**
This is another attempt at the new design with some various changes from the original. Ping @joecohens :)

Some key changes & features:

- Unified header and navigation bar
- Simple "Powered by Cachet" footer (still optional) but can display the timezone too
- Improved component designs, including status icons
- A proper design for Incident Updates
- We only show the last `x` (default 3) days of incidents. There is a link to take you to an overview of the previous incidents

### CODE REVIEW

**Comment by gabel** [comment]
@jbrooksuk How about some preview screens for discussion?

**Comment by jbrooksuk** [comment]
@gabel sure. I've started a rudimentary HTML version at https://gist.github.com/jbrooksuk/fa291f5d8016a0dc64ee6ac112568253 based on a design by @thomasHolman.

[Status.pdf](https://github.com/CachetHQ/Cachet/files/775053/Status.pdf)

**Comment by mm-manageit** [comment]
That looks great!!!

**Comment by jbrooksuk** [comment]
Glad you like it @mm-manageit! I've updated the original PR message to include an overview of the changes.

**Comment by franzliedke** [comment]
Looks very pretty. 👍 

IMO, there should be more contrast for some of the texts, though. You can use an [online contrast checker](http://webaim.org/resources/contrastchecker/) to make sure the design conforms to the W3C's accessibility standards.

**Comment by jbrooksuk** [comment]
@franzliedke absolutely. Feel free to make a PR from this branch fixing up anything :)

**Comment by jbrooksuk** [comment]
Rebased.

**Comment by willallen** [comment]
@jbrooksuk looks awesome! any thoughts on how scheduled maintenance could be displayed?

**Comment by jbrooksuk** [comment]
@willallen none yet, probably how it is currently, but then the Schedules will drop into the "Past Incidents" section.

**Comment by jbrooksuk** [comment]
Since this requires a rather large rewrite, I'd be tempted to look into using Tailwind CSS at this point. What do people think?

**Comment by franzliedke** [comment]
@jbrooksuk Please don't. IMHO, Tailwind and the like are not suited for webapps that might receive different theming (that goes further than changing the color scheme). And to me, Cachet is such a webapp. :wink:

**Comment by jbrooksuk** [comment]
Discussing this in #3111.

**Pull request closed without merging**
