### PR TITLE
Per-component subscriptions

### LINKED ISSUE #734: Subscribe to specific components
I have some cool ideas for V2 :

- Might be cool to subscribe to specific components only for some users
- Multiple client dashboards (separated)?

If this is not the place for ideas, please let me know haha!

### PR DESCRIPTION
**Pull request by jbrooksuk**
Aside from tests, I think the core system works for this, just need a UI now to manage preferences.

Closes #734

### CODE REVIEW

**Comment by jbrooksuk** [comment]
For now, rather than a UI for managing preferences, how about an unsubscribe from component link in the email itself? Ping @joecohens

**Comment by joecohens** [comment]
Yeah we need a way to unsubscribe from a single component as well

**Comment by jbrooksuk** [comment]
@joecohens do you believe this to be ready and finished?

**Comment by joecohens** [comment]
I think we are just missing the link to unsubscribe to a specific component. We could attach it to the current one.

**Comment by jbrooksuk** [comment]
Are you ok adding this in?

**Comment by joecohens** [comment]
Adding it now :)

**Comment by jbrooksuk** [comment]
Seems to work fine Joe! Squash and merge?

**Comment by jbrooksuk** [comment]
Squashed. Waiting on tests then we can merge!

**Comment by joecohens** [comment]
:raised_hands:

**Comment by txsteven** [comment]
Currently on 2.1.0 so forgive me if this is addressed in 2.1.1 But If I subscribe to only component A. And I create an incident on Component B. The user who has only subscribed to A still gets the notification. Is this working as designed or a bug fixed in 2.1.1?  

Respectfully,

**Comment by jbrooksuk** [comment]
Ping @joecohens, this doesn't sound right?

**Comment by joecohens** [comment]
Mmm I think we didn't filter subscriptions on the incidents, we only did when you update the a component. But I'm not sure if we should, because they are different subscriptions, one is site wide (all incidents) and the other one it's just for component updates not it's incidents. @jbrooksuk we need to review the functionality.

https://github.com/CachetHQ/Cachet/blob/master/app/Bus/Handlers/Events/Component/SendComponentUpdateEmailNotificationHandler.php#L59

https://github.com/CachetHQ/Cachet/blob/master/app/Bus/Handlers/Events/Incident/SendIncidentEmailNotificationHandler.php#L68

**Pull request merged**
