### PR TITLE
Component groups sorted by status and order

### PR DESCRIPTION
**Pull request by billmn**
Related to https://github.com/CachetHQ/Cachet/issues/2100

Now groups are ordered by severity status and specified order.

### CODE REVIEW

**Comment by jbrooksuk** [comment]
How does this affect the component group ordering?

**Comment by GrahamCampbell** [comment]
We should instead define the original relationship to be sorted perhapse rather than doing a client side sort.

**Comment by GrahamCampbell** [comment]
The client being the PHP server in this cas.

**Comment by billmn** [comment]
@GrahamCampbell @jbrooksuk Yep, this allow to keep the same default order in an API response.

**Comment by jbrooksuk** [comment]
@GrahamCampbell there is no relationship that we originally fetch the groups from. We're ordering the groups, not the components in this PR.

**Comment by billmn** [comment]
@GrahamCampbell @jbrooksuk This order must be the same on the API?

**Comment by jbrooksuk** [comment]
Yeah, I'd say so. Consistency. Although that said, the API allows for sorting.

**Comment by billmn** [comment]
@jbrooksuk @GrahamCampbell 

What about this query scope for ComponentGroup model that extract the group severity?

```php
public function scopeWithSeverity(Builder $query)
{
    $subquery = 'SELECT group_id, MAX(status) as severity FROM components GROUP BY group_id';

    return $query->join(DB::raw("($subquery) as sq"), 'group_id', '=', 'id');
}
```

After that in <code>Api\ComponentGroupController</code> we can do this:
```php
public function getGroups()
{
    $groups = ComponentGroup::withSeverity();

    if (!$this->guard->check()) {
        $groups->visible();
    }

    $groups->search(Binput::except(['sort', 'order', 'per_page']));

    if ($sortBy = Binput::get('sort')) {
        $direction = Binput::get('order', 'asc');
        $groups->sort($sortBy, $direction);
    } else {
        $groups->orderBy('severity', 'desc')->orderBy('order');
    }

    $groups = $groups->paginate(Binput::get('per_page', 20));

    return $this->paginator($groups, Request::instance());
}
```

And this in <code>ComponentsComposer</code>:
```php
public function compose(View $view)
{
    $componentGroups = $this->getVisibleGroupedComponents();
    $ungroupedComponents = Component::ungrouped()->get();

    $view->withComponentGroups($componentGroups)
        ->withUngroupedComponents($ungroupedComponents);
}

/**
 * Get visible grouped components.
 *
 * @return \Illuminate\Support\Collection
 */
protected function getVisibleGroupedComponents()
{
    $componentGroupsBuilder = ComponentGroup::withSeverity()
        ->orderBy('severity', 'desc')
        ->orderBy('order');

    if (!$this->guard->check()) {
        $componentGroupsBuilder->visible();
    }

    $usedComponentGroups = Component::grouped()->pluck('group_id');

    return $componentGroupsBuilder->used($usedComponentGroups)
        ->get();
}
```

**Comment by ConnorVG** [comment]
Not sure about anyone else but seeing `DB::raw` makes me want to rip my eyeballs out.

**Comment by billmn** [comment]
@ConnorVG Is only an example to show you what I think to do. We can try to get the same thing using the query builder.

**Comment by billmn** [comment]
@jbrooksuk @GrahamCampbell Thoughts on this?

**Comment by jbrooksuk** [comment]
Looks okay to me. @GrahamCampbell?

Like @ConnorVG said, that `DB::raw` is making me sad.

**Comment by billmn** [comment]
@jbrooksuk @ConnorVG Agree, I'm trying to figure out how to execute this subquery without <code>DB::raw</code> ... any suggestions?

**Comment by ConnorVG** [comment]
Use Eloquent?

`SELECT group_id, MAX(status) as severity FROM components GROUP BY group_id` ->
```php
$query->selectRaw('MAX(status) as severity')
    ->addSelect('group_id')
    ->groupBy('group_id');
```

idk about merging it into the scope though, I'm at work atm so I can't test anything.

**Comment by billmn** [comment]
@ConnorVG Yes the problem is merging the scope, not create the query :)

**Comment by jbrooksuk** [comment]
Assigned to @ConnorVG and @billmn to figure out :)

**Comment by billmn** [comment]
@ConnorVG what about this? I don't think there are SQL injection points.

```php
/**
 * Add status severity.
 *
 * @param \Illuminate\Database\Eloquent\Builder $query
 * @return \Illuminate\Database\Eloquent\Builder
 */
public function scopeWithSeverity(Builder $query)
{
    $subquery = Component::selectRaw('MAX(status) as severity')
        ->addSelect('group_id')
        ->groupBy('group_id');

    return $query->join(DB::raw("({$subquery->toSql()}) as sq"), 'group_id', '=', 'id');
}
```

**Comment by billmn** [comment]
Ping @jbrooksuk

**Comment by ConnorVG** [comment]
@billmn that seems equally as bad to me :disappointed:

**Comment by billmn** [comment]
@ConnorVG I don't know an other way to do this. I don't think this query can cause security vulnerability

**Comment by jbrooksuk** [comment]
@ConnorVG what's the plan on this?

**Comment by jbrooksuk** [comment]
Any movement?

**Comment by billmn** [comment]
I don't see ecurity issues in my proposal ... If you agree I can PR

**Comment by jbrooksuk** [comment]
@ConnorVG thoughts?

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.

**Pull request closed without merging**
