### PR TITLE
Upgrade to elixir 4 and rebuild assets

### PR DESCRIPTION
**Pull request by joecohens**
Closes https://github.com/cachethq/Cachet/issues/1184

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Wow this was quick!

**Comment by joecohens** [comment]
Trying a new app to get GitHub notifications quicker ;)

**Comment by jbrooksuk** [comment]
Oh yeah?

**Comment by joecohens** [comment]
https://github.com/ekonstantinidis/gitify I just built it myself, I'll let you know how it works for me :smile:

**Comment by GrahamCampbell** [comment]
> Trying a new app to get GitHub notifications quicker ;)

**Comment by GrahamCampbell** [comment]
> Trying a new app to get GitHub notifications quicker ;)

That would destroy my day, lol.

**Comment by joecohens** [comment]
Lol it would definitely destroy your day. 😜

**Pull request merged**
