### PR TITLE
Solely use Carbon

### PR DESCRIPTION
**Pull request by jbrooksuk**
We don't need to use jenssegers/date as Carbon should be doing everything we need.

### CODE REVIEW

**Comment by joecohens** [comment]
Using `jenssegers/date` it's just because of the lang translations https://github.com/jenssegers/date#languages, it's a "wrapper" for carbon including all the translations ;)

**Comment by jbrooksuk** [comment]
From what I can tell, Carbon has translations too? 
https://github.com/briannesbitt/Carbon/tree/master/src/Carbon/Lang

**Comment by joecohens** [comment]
😱 They added them one month ago! That's very cool, now we can safely remove the package.

**Comment by jbrooksuk** [comment]
Happy to merge this then? I can't see why it'd stop working. I've added `Carbon::setLocale` too, so that should help!

**Comment by joecohens** [comment]
😉

**Comment by GrahamCampbell** [comment]
Awesome to kill that unneeded library. :D

**Comment by jbrooksuk** [comment]
Best thing is removing code!

**Pull request merged**
