### PR TITLE
Auto-link Twitter handles

### LINKED ISSUE #2380: Twitter Markdown extension
I've seen a few incidents around that link to Twitter pages. What do people think about auto-linking `@handle` text in Incident messages?

### PR DESCRIPTION
**Pull request by jbrooksuk**
Closes #2380

---

I'll merge this if enough people will find this beneficial. We could hide this behind a setting though.

### CODE REVIEW

**Comment by mm-manageit** [comment]
I would vote for having it attached to a setting, as for our use cases I think it would be more annoying than helpful. Though on the flipside, can see it being useful for other use cases that utilize twitter alot for communication.

**Comment by GrahamCampbell** [comment]
Would be better to have this as an Alt Three package.

👎 For the setting. Just have it on by default in the config, same as for emojis.

**Comment by jbrooksuk** [comment]
> I would vote for having it attached to a setting

It'll be a setting.

> Would be better to have this as an Alt Three package.

Can do this.

**Comment by jbrooksuk** [comment]
Replaced by #2404

**Pull request closed without merging**
