### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by CachetBot**
Enjoy!

### CODE REVIEW

**Comment by Atriusftw** [comment]
Yay. Seems like the translations are correctly split by version now 👍
Is it intentional that you want to merge in non-approved translations aswell?

**Comment by jbrooksuk** [comment]
That’s weird... I’d have thought we’d only be showing merged/approved translations.

**Comment by jbrooksuk** [comment]
This may be a setting I can change. I’ll have a look now.

**Comment by jbrooksuk** [comment]
Okay, this should now be fixed. It does mean that we need more effort behind approving all translations, so we’ll see how it goes.

**Comment by jbrooksuk** [comment]
I believe this **may** revert a lot of translations that have been available but are not approved. Let's see what happens.

**Comment by Atriusftw** [comment]
@jbrooksuk The files in `resources/lang/no/` are not being updated, which actually are the ones being used by browsers.

Edit: Seems like this applies to all languages with two or more versions.

**Comment by Atriusftw** [comment]
@jbrooksuk Ref. my last comment - is this something you could have a look at?

**Comment by jbrooksuk** [comment]
Sorry, what do you mean the ones being used by browsers?

**Comment by Atriusftw** [comment]
If i have the site language set to English, and check "Automatically localise your status page to your visitor's language?", as a guest with a norwegian browser i get the translations from the no-NO folder, which is outdated and seemingly not updated by your crowdin script.

**Comment by Atriusftw** [comment]
@jbrooksuk I'm sorry to bring this one up again, but is this something you can have a look into? If you need more information, please let me know.

**Pull request merged**
