### PR TITLE
[WIP] Added presenters and timezone locales with diff and popover

### PR DESCRIPTION
**Pull request by joecohens**
**Caution**: Don't merge this until https://github.com/ShawnMcCool/laravel-auto-presenter gets updated on packagist.

Added presenters, and localisation on Status Page dates.

Closes https://github.com/cachethq/Cachet/issues/192

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Looks like Packagist has updated. It's showing as `2.2.x-dev reference: 79e1eab`.

**Comment by jbrooksuk** [comment]
Tests fail because `View` is not found within the package, @joecohens do you need to change the package version?

**Comment by GrahamCampbell** [comment]
Yes, add the dev annotation to the version constaint until I tag another release.

**Comment by joecohens** [comment]
Sure I'll do that now :)

**Comment by joecohens** [comment]
Done :) I've updated the package and rebased.

**Comment by jbrooksuk** [comment]
Awesome, let's merge.

**Pull request merged**
