### PR TITLE
Update polish translation

### PR DESCRIPTION
**Pull request by desavil**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please send to crowdin. The language files are autogenerated.

**Comment by GrahamCampbell** [comment]
https://github.com/CachetHQ/Cachet/blob/2.4/CONTRIBUTING.md#languages

**Comment by desavil** [comment]
I updated all Polish translations on https://translate.cachethq.io/project/cachet/pl
There were a lot of mistakes and a lot of German translations.

Please approve and build.

**Comment by jbrooksuk** [comment]
Awesome, will do.

**Pull request closed without merging**
