### PR TITLE
Fix status page subscribe button style

### PR DESCRIPTION
**Pull request by joecohens**
@jbrooksuk This will fix the bug @TheoBearman pointed about the subscribe button on the status page.

### CODE REVIEW

**Comment by TheoBearman** [comment]
Thanks bae.

**Comment by joecohens** [comment]
:smile:

**Comment by GrahamCampbell** [comment]
Assets will need compiling. TBH, we could probs setup a bot that does this by looking at what files are modified.

**Comment by jbrooksuk** [comment]
We definitely should have a bot compiler.

**Comment by TheoBearman** [comment]
This doesn't seem to have fixed it. Home button on the subscriber page has the same issue.

**Comment by jbrooksuk** [comment]
I've just had to re-compile the assets @TheoBearman, pull and try again?

**Comment by TheoBearman** [comment]
Still doesn't look to be working. Check my install to confirm as I'm on a mobile. Could it be a caching issue?

**Comment by jbrooksuk** [comment]
Yeah, still an issue. I'll have to look later I'm afraid.

**Comment by TheoBearman** [comment]
No worries mate.

**Comment by joecohens** [comment]
@jbrooksuk @TheoBearman Whoops, sorry my fault forgot an !important rule. Fixed in https://github.com/CachetHQ/Cachet/pull/1623

**Pull request merged**
