### PR TITLE
User can login with username or email

### PR DESCRIPTION
**Pull request by phecho**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
If we do want to allow this, then this looks ok to me. :+1:

**Comment by phecho** [comment]
@GrahamCampbell 
I suggest that this feature is enabled for two reasons:
1,  Both of username and email are unique index.
2,  If username can't be logged in, it is easy to forget, there is no need to exist.

**Comment by GrahamCampbell** [comment]
Well if @jbrooksuk and @joecohens give it a :+1:, then it'll get merged in. ;)

**Comment by jbrooksuk** [comment]
Works! :)

**Comment by joecohens** [comment]
:+1:

**Comment by joecohens** [comment]
lol

**Pull request merged**
