### PR TITLE
Make footer simpler

### PR DESCRIPTION
**Pull request by joecohens**
screen shot 2015-10-24 at 12 47 58 pm

/cc @jbrooksuk

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Travis is sad.

**Comment by GrahamCampbell** [comment]
I'll fix travis and rebase this for you.

**Comment by GrahamCampbell** [comment]
Meh, merging. Looks pretty nice to me.

Let us know if there's anything you want changing @jbrooksuk. :)

**Comment by jbrooksuk** [comment]
:+1:

**Comment by TheoBearman** [comment]
Sorry to be really nitpicky but there appears to be an extra space before the words 'Dashboard', 'RSS' and 'Atom' when the links are hovered over.

xaa

**Comment by GrahamCampbell** [comment]
@TheoBearman Could you open a new issue please?

**Pull request merged**
