### PR TITLE
feat: FORCE_HTTPS_URLS env to force \URL schemes to https

### PR DESCRIPTION
**Pull request by lbennett-stacki**
For https://github.com/CachetHQ/Docker/issues/158

 I have cachet behind SSL terminating load balancer. Cachet is rendering pages with assets to request using the `http` protocol. Browsers will block these assets if you are accessing over https, even if the asset ingress forces redirects.

### CODE REVIEW

**Comment by ChrisTG742** [comment]
We use this fix here and it's working fine. Please consider merging it into base repo.

**Comment by arrfab** [comment]
Came here because of the same issue and wondering when that simple fix can be merged as it seems it's affecting quite some users when running cachethq behind TLS balancer/reverse proxy.
Don't know what's the best approach for the time being to easily deploy the container, maybe apply the patch and rebuild a container and so not deploy the official one ?

**Comment by arrfab** [comment]
some links for issues : 
#3952

**Comment by arrfab** [comment]
FWIW (for people willing to use it as container), I just built this for my own usage : https://quay.io/repository/farrotin/cachethq
So basically : 
 * using original/upstream container image
 * applying this patch

**Pull request closed without merging**
