### PR TITLE
Trust proxies in local IPs

### PR DESCRIPTION
**Pull request by vitorbaptista**
This allows CachetHQ to be served behind proxies
running in the local network (e.g. a Docker container).

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Ping @GrahamCampbell @joecohens

**Comment by djdefi** [comment]
It would be cool if this was something configurable via Environment variable / `.env` file, which would help to further address https://github.com/CachetHQ/Docker/issues/160 - Make it configurable and overridable.

**Comment by vitorbaptista** [comment]
@djdefi Definitely! Because of this issue, I opened https://github.com/fideloper/TrustedProxy/issues/81 on TrustedProxy to see if there's interest in allowing this to be configured via env variables in the library level.

**Comment by GrahamCampbell** [comment]
Looks good to me.

**Comment by GrahamCampbell** [comment]
👍

**Comment by joecohens** [comment]
Looks good to me too, thanks for also opening the issue on TrustedProxies @vitorbaptista

**Pull request merged**
