### PR TITLE
Improvements to the exception handler

### PR DESCRIPTION
**Pull request by GrahamCampbell**
What do you make of this @cachethq/owners?

### CODE REVIEW

**Comment by joecohens** [comment]
I would still like to have the json response for the API can we use the displayers?

**Comment by jbrooksuk** [comment]
I agree with @joecohens, we could still use the JSON response too.

**Comment by GrahamCampbell** [comment]
We are sending back a json response though?

**Comment by jbrooksuk** [comment]
Oh yeah, merge ahead :)

**Comment by GrahamCampbell** [comment]
We're sending back a response with that error information because it's an http exception, so we keep the exception message in the response.

**Comment by GrahamCampbell** [comment]
Making a json response in that way for our api is bad. We don't even know if the user understands json.

**Comment by GrahamCampbell** [comment]
This way we're manipulating the exception, then letting the exception handler return a response the user understands.

**Comment by GrahamCampbell** [comment]
Though we do have an issue here because if they set their accept header to `*` they will get an html error page, though that's technically the fault of the client.

**Pull request merged**
