### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by ApfelUser**
https://crowdin.com/translate/cachet/9/en-de#435

### CODE REVIEW

**Comment by ApfelUser** [comment]
:disappointed: no clue why StyleCI and Scrutinizer are failing. You guys can kick off the German crowdin build please by the way.

**Comment by jbrooksuk** [comment]
Rebuilt the translations.

**Comment by jbrooksuk** [comment]
StyleCI failed because of the double quotes. Can you fix that and squash commits please?

**Comment by GrahamCampbell** [comment]
Yeh, we updated our fixer definitions as planned on 9th April. We were going to have a blog post ready, but it's not done yet. We were advertising the change on login since April 2nd.

**Comment by ApfelUser** [comment]
So you mean it should be " instead of ' ?

**Comment by jbrooksuk** [comment]
@ApfelUser you can apply the patch that StyleCI provides :)

**Comment by GrahamCampbell** [comment]
Yeh, one of the new rules in the "recommended" preset is that when a string is simple, then single quotes should be preferred to double quotes.

**Comment by ApfelUser** [comment]
Hm. Not to familiar with applying these diffs :smiley: I could do it myself but the problem is that StyleCI seems to want to change `"` to `'`, but when I look at the source they already are all changed to`'`.

**Comment by GrahamCampbell** [comment]
@ApfelUser Is your fork out of date?

**Comment by ApfelUser** [comment]
@GrahamCampbell it was, but after updating I still have only `'`.

My editor:

cachet

But also on GitHub:

cachet2

**Comment by GrahamCampbell** [comment]
Yes, the file you are looking at already has single quotes. Not go and look at the same file in the fr folder...

**Comment by GrahamCampbell** [comment]
https://i.starbs.net/3o3N

**Comment by jbrooksuk** [comment]
Will merge and fix.

**Pull request merged**
