### PR TITLE
Upgrade to Laravel 5.6

### LINKED ISSUE #2666: Upgrade to Laravel 5.5

### LINKED ISSUE #2669: Remove GrahamCampbell/Laravel-Core
The package is now abandoned.

We should move things into the `cachet` signature.

### LINKED ISSUE #2862: Changes to Count() in PHP 7.2 Cause 500 internal Error.
Using:
Windows Server 2016
Cachet 2.3.9
PHP 7.2
Apache 2.4

After completing the install I get the 500 Internal Server Error. When I look in the error logs I see the following.
[Mon Jan 08 11:32:13.533024 2018] [php7:error] [pid 6812:tid 1052] [client 127.0.0.1:59375] PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in E:\\Cachet Status Page\\cachet\\vendor\\graham-campbell\\exceptions\\src\\ExceptionIdentifier.php:51\nStack trace:\n#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'count(): Parame...', 'E:\\\\Cachet Statu...', 51, Array)\n#1 E:\\Cachet Status Page\\cachet\\vendor\\graham-campbell\\exceptions\\src\\ExceptionIdentifier.php(51): count(NULL)\n#2 E:\\Cachet Status Page\\cachet\\vendor\\graham-campbell\\exceptions\\src\\ExceptionHandlerTrait.php(47): GrahamCampbell\\Exceptions\\ExceptionIdentifier->identify(Object(ErrorException))\n#3 E:\\Cachet Status Page\\cachet\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(79): GrahamCampbell\\Exceptions\\ExceptionHandler->report(Object(ErrorException))\n#4 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(ErrorException))\n#5 {main}\n  thrown in E:\\Cachet Status Page\\cachet\\vendor\\graham-campbell\\exceptions\\src\\ExceptionIdentifier.php on line 51

[Mon Jan 08 11:32:13.533024 2018] [php7:error] [pid 6812:tid 1052] [client 127.0.0.1:59375] PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in E:\\Cachet Status Page\\cachet\\vendor\\graham-campbell\\exceptions\\src\\ExceptionIdentifier.php:51\nStack trace:\n#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'count(): Parame...', 'E:\\\\Cachet Statu...', 51, Array)\n#1 E:\\Cachet Status Page\\cachet\\vendor\\graham-campbell\\exceptions\\src\\ExceptionIdentifier.php(51): count(NULL)\n#2 E:\\Cachet Status Page\\cachet\\vendor\\graham-campbell\\exceptions\\src\\ExceptionHandlerTrait.php(47): GrahamCampbell\\Exceptions\\ExceptionIdentifier->identify(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#3 E:\\Cachet Status Page\\cachet\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(79): GrahamCampbell\\Exceptions\\ExceptionHandler->report(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#4 E:\\Cachet Status Page\\cachet\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExcept in E:\\Cachet Status Page\\cachet\\vendor\\graham-campbell\\exceptions\\src\\ExceptionIdentifier.php on line 51

After doing a bit of googling it seems there was a change to Count in PHP 7.2 that is the cause of this.

### PR DESCRIPTION
**Pull request by jbrooksuk**
Closes #2862, closes #2666, closes #2669

---

## To-do

- [x] Upgrade core dependencies to Laravel 5.6
- [x] Update all Blade variables to use camelCase
- [x] Fix tests
- [x] Update `.travis.yml` to drop PHP 5.6 support
- [x] Fix settings log view now that `Writer` has gone
- [x] Fix `./tests/TestListener.php`
- [x] Update Laravel Backup Manager

### CODE REVIEW

**Comment by nstapelbroek** [comment]
This is amazing :tada: will check this week if I can help

**Comment by jbrooksuk** [comment]
Laravel-Core is being replaced in a separate PR (https://github.com/CachetHQ/Cachet/pull/3092) so we should aim to get that done first, making this easier. We also need to try and get this done quickly so that the view variables don't become too much of a pain.

**Comment by jbrooksuk** [comment]
I've replaced Backup-Manager with `spatie/laravel-backups`.

**Comment by jbrooksuk** [comment]
Just need tests to pass and then we *should* 🤞 be updated!

**Comment by jbrooksuk** [comment]
Tests are failing, darn it!

**Comment by joecohens** [comment]
❤️

**Pull request merged**
