### PR TITLE
Re-sync languages

### LINKED ISSUE #1490: Site language bug ? Weird translation problems
Hey there,
I'm trying version 2.1.1-dev, I upgraded from old version.
Language in dashboard is set to French and next to services there is `Funktionsfähig`.
I also tried to set language to english and same problem.

See in this screenshot for more informations.
cachet-translation

### PR DESCRIPTION
**Pull request by jbrooksuk**
Closes #1490

Ping @bbcorp - can you check the French translations look ok? We can re-sync them before releasing on Saturday.

### CODE REVIEW

**Comment by bbcorp** [comment]
> Ping @bbcorp - can you check the French translations look ok? We can re-sync them before releasing on Saturday.

Will do tonight. I keep you informed.

**Comment by carsso** [comment]
In this branch, status are still in German and not translated in any language.

See [this](https://github.com/CachetHQ/Cachet/blob/sync-langs/resources/lang/fr/cachet.php#L15) if you need an example ([this old version of the file](https://github.com/CachetHQ/Cachet/blob/f19b0d1a463b3dd0c5eba3155d1f9af8c0d70207/resources/lang/fr/cachet.php#L17) is correctly translated).
E.g. 'Funktionsfähig' translated in french is 'Opérationnel'

**Comment by GrahamCampbell** [comment]
Ping @jbrooksuk.

**Comment by jbrooksuk** [comment]
Is CrowdIn showing the right translations?

**Comment by carsso** [comment]
Yes,  see https://crowdin.com/translate/cachet/1/en-fr

'Opérationnel' is the right French translation for 'Funktionsfähig'

**Comment by carsso** [comment]
My bad, CrowdIn in the French page (https://crowdin.com/translate/cachet/1/en-fr), CrowdIn is showing the word in German instead of the French one.
Let's summarize:
'Operational' in French is 'Opérationnel'
CrowdIn says 'Operational' in French is 'Funktionsfähig' (the German translation) [see here](https://crowdin.com/translate/cachet/1/en-fr)
But the [old version of the file](https://github.com/CachetHQ/Cachet/blob/f19b0d1a463b3dd0c5eba3155d1f9af8c0d70207/resources/lang/fr/cachet.php#L17) is correctly translated in french.
There is a mess somewhere...

**Comment by jbrooksuk** [comment]
I've corrected the translations :)

Targeting this to 2.1 though, so closing it.

**Comment by bbcorp** [comment]
Hey James,
sorry to bother you again, but the french translations are wrong again. See l29 of [cachet.php](https://github.com/CachetHQ/Cachet/blob/62a654a290e7f7784e261923dee6dcdd171c9fbf/resources/lang/fr/cachet.php#L29).
Basically on Crowdin all approved translation under 0 votes or number of votes under the next translation are wrong. Most of theses wrong translations was approved 3 months agos for information.
I did correct some translation but need approvement.
Could you please re-check Crowdin and re-approve the right translations ?
Thanks in advance

**Comment by carsso** [comment]
@jbrooksuk @bbcorp I've checked all french translation files and here is an exhaustive list of translations with a problem (mostly because on CrowdIn, the approved translation is the wrong one) :

resources/lang/fr/cachet.php:
array['incidents']['scheduled'] [CrowdIn](https://crowdin.com/translate/cachet/1/en-fr#438)
array['api']['revoke'] [CrowdIn](https://crowdin.com/translate/cachet/1/en-fr#304)

resources/lang/fr/dashboard.php:
array['settings']['localization']['localization'] [CrowdIn](https://crowdin.com/translate/cachet/9/en-fr#584)

resources/lang/fr/forms.php:
array['components']['enabled'] [CrowdIn](https://crowdin.com/translate/cachet/11/en-fr#587)
array['components']['groups']['collapsed'] [CrowdIn](https://crowdin.com/translate/cachet/11/en-fr#654)
array['settings']['theme']['banner-background-color'] [CrowdIn](https://crowdin.com/translate/cachet/11/en-fr#601)
array['settings']['theme']['banner-padding'] [CrowdIn](https://crowdin.com/translate/cachet/11/en-fr#602)
array['settings']['theme']['fullwidth-banner'] [CrowdIn](https://crowdin.com/translate/cachet/11/en-fr#603)
array['user']['levels']['admin'] [CrowdIn](https://crowdin.com/translate/cachet/11/en-fr#614)
array['user']['team']['description'] [CrowdIn](https://crowdin.com/translate/cachet/11/en-fr#616)
array['user']['team']['email'] [CrowdIn](https://crowdin.com/translate/cachet/11/en-fr#617)

**Comment by jbrooksuk** [comment]
Okey dokey, thanks guys.

**Pull request closed without merging**
