### PR TITLE
Laravel 5.4

### PR DESCRIPTION
**Pull request by jbrooksuk**
Because why the heck not?!

--- 

TODO:

- [x] Fix tests - `composer require laravel/browser-kit-testing`
- [x] Update remaining config files
- [x] Check all dependencies are up to date

### CODE REVIEW

**Comment by base-zero** [comment]
@jbrooksuk Is it worth waiting and upgrading to Laravel 5.5 as it's an LTS version ?

**Comment by ConnorVG** [comment]
@base-zero we would end up upgrading to 5.5 anyway, 5.4 would still be a middle step

**Comment by jbrooksuk** [comment]
Doing the upgrade step-by-step is favoured. I'll try to finish this upgrade ASAP.

**Comment by jbrooksuk** [comment]
Tests pass locally and I'm able to use the app myself. If anyone spots anything broken, hit me up!

**Pull request merged**
