### PR TITLE
New backoffice theme

### PR DESCRIPTION
**Pull request by joecohens**

### CODE REVIEW

**Comment by jbrooksuk** [comment]
@joecohens you know I :heart: this. Merge when you're ready!

**Comment by joecohens** [comment]
Just a little refresh :smile:

**Comment by GrahamCampbell** [comment]
Needs rebasing?

**Comment by joecohens** [comment]
Rebased :wink:

**Comment by TheoBearman** [comment]
Really excited to see this...

**Comment by GrahamCampbell** [comment]
The login page looks a bit odd:

image

**Comment by joecohens** [comment]
@GrahamCampbell You need to rebuild assets

**Comment by TheoBearman** [comment]
Surely the box should be green not white?

**Comment by joecohens** [comment]
I'll rebuild them after merge

**Comment by jbrooksuk** [comment]
MERGED! Rebuild!

**Comment by jbrooksuk** [comment]
I'm on it.

**Comment by TheoBearman** [comment]
https://status.theobearman.com/

Footer 'Subscribe' button is not right surely?

**Comment by joecohens** [comment]
Thanks @TheoBearman !!! I'll fix that ASAP :)

**Pull request merged**
