### PR TITLE
Fixes error on postgresql on 2FA column

### PR DESCRIPTION
**Pull request by joecohens**
Fixes https://github.com/cachethq/Cachet/issues/346

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I think this caused issues with mysql 5.6.

**Comment by joecohens** [comment]
I've tested on the latest version of Homestead with MySQL Distrib 5.6.19, for debian-linux-gnu (x86_64) and (PostgreSQL) 9.4.0. Maybe for another dist?

**Comment by GrahamCampbell** [comment]
Also, this shouldn't be a separate migration file anyway. We should just be editing the existing migrations until we actually tag v1.0.0.

**Comment by joecohens** [comment]
Yeah that's true, this is only fixing one click install on Heroku for now.

**Comment by jbrooksuk** [comment]
Cool.

**Pull request merged**
