### PR TITLE
Namespaced Models And Refactored Filters

### PR DESCRIPTION
**Pull request by GrahamCampbell**
BOOM!

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
// cc @jbrooksuk, @joecohens

**Comment by joecohens** [comment]
This is so beautiful ! Excellent work !

**Comment by GrahamCampbell** [comment]
Just pushed some fixes. Are we good to merge?

**Comment by GrahamCampbell** [comment]
NB, the scrutinizer score went down a bit because now we've actually analysing the models.

**Comment by joecohens** [comment]
Sorry I couldn't test it I was away, I'll try it now.

**Comment by joecohens** [comment]
@GrahamCampbell I've pushed an quick fix for auth user. https://github.com/cachethq/Cachet/commit/f8f652514ed0813b6891549d2ed0e52a56b834cd

**Comment by GrahamCampbell** [comment]
Thanks

**Pull request merged**
