### PR TITLE
Command Tests

### LINKED ISSUE #942: Add Command/Event Tests Like StyleCI
This stuff is brilliant for checking for typos and missing assignments, and will also check the handlers can be instantiated, but doesn't test actual handler execution.

I'll get this done asap.

### PR DESCRIPTION
**Pull request by jbrooksuk**
This will close #942.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Shall I make an Alt Three TestBench pacage so we don't have to duplicate the bas stuff?

**Comment by jbrooksuk** [comment]
That'd be super useful since both StyleCI and Cachet use the exact same abstract code.

**Comment by jbrooksuk** [comment]
Merging this now then and we'll just refactor later on.

**Comment by GrahamCampbell** [comment]
Sure.

**Comment by GrahamCampbell** [comment]
Maybe now is a good time to tag v2.0.0-beta2?

**Pull request merged**
