### PR TITLE
Remove converting timezone for fetching

### PR DESCRIPTION
**Pull request by joecohens**
/cc @CachetHQ/owners 

Fixes https://github.com/CachetHQ/Cachet/issues/1357

### CODE REVIEW

**Comment by vogelor** [comment]
Sorry, but there is stil a little flaw.
i now have the time 15:52 (3:52 PM). The graph still shows all the ponts until 15:00 but not the points 15:01-15:52. Means the actuall hour (not completelly full) is NOT shown...

**Comment by GrahamCampbell** [comment]
This is a know bug, and is a different bug.

**Comment by GrahamCampbell** [comment]
The same issue is present with looking at the current day in weekly view.

**Comment by GrahamCampbell** [comment]
https://github.com/CachetHQ/Cachet/issues/1356

**Pull request merged**
