### PR TITLE
Add tag names array to components API

### LINKED ISSUE #1697: Component tags missing from API response?
Tags seem like a great place to store some meta-data for a docker integration i'm toying with..

### PR DESCRIPTION
**Pull request by jbrooksuk**
Closes #1697 

---

Ping @jrabbit for this, is this what you'd expect to see?

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Would you rather have an array of tag names, or a key/value pair of slug/names which would make the Tags API easier to use - once implemented.

**Comment by jbrooksuk** [comment]
Merging this once tests have passed. We now use `"slug": "name"` pairs.

**Comment by jbrooksuk** [comment]
Documentation updated to reflect this.

**Comment by jrabbit** [comment]
looks good!

**Pull request merged**
