### PR TITLE
Remove docker/homestead/vagrant stuff

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by wfjsw** [comment]
@jbrooksuk I will try to fork the project to maintain docker version

**Comment by rtrauntvein** [comment]
@wfjsw there is a new repo that @jbrooksuk has setup for the docker portion https://github.com/cachethq/Docker

**Comment by wfjsw** [comment]
@rtrauntvein The current code has no problem, but a different install way is needed, I think.
My suggest: Mount .env volume instead of set Environment Variables

**Comment by rtrauntvein** [comment]
That could be done currently as is - Keeping support for both mounting a config as well as setting via environment variables is pretty straightforward, and keeps everything to a http://12factor.net/ app

**Comment by jbrooksuk** [comment]
Please don't fork the repo, instead use CachetHQ/Docker as @rtrauntvein said :) I've replied to your email now @wfjsw

**Comment by jbrooksuk** [comment]
@cachethq/docker let us know once we're good to go please.

**Comment by GrahamCampbell** [comment]
Merging since the latest docker version is 1.1.1. Anyone using non-released code should expect issues. This should be a wakeup call for anyone doing that.

**Comment by GrahamCampbell** [comment]
In order to port the docker stuff, you're going to need the browse the code from this point: https://github.com/cachethq/Cachet/tree/c05e9d9867242768bcb14b00fd90637208fde168.

**Comment by jbrooksuk** [comment]
Maybe we need a tweet/email for this too?

**Comment by GrahamCampbell** [comment]
> Maybe we need a tweet/email for this too?

No, because we're not releasing anything.

**Comment by GrahamCampbell** [comment]
Why is making this change on the 1.2 branch any different to making it on a branch called remove?

**Comment by radum** [comment]
And where is Vagrant? I see the new repo for it, but it is empty.

**Comment by jbrooksuk** [comment]
None of us use Vagrant, so not sure how to get it to setup from a remote repository. Feel free to contribute :)

**Comment by radum** [comment]
@jbrooksuk Oh OK, wasn't sure why it was removed. I would rather use Homestead instructions for it, because it already uses Vagrant in the background and it is supported by Laravel. I will git it a try and submit a PR this week.

**Comment by jbrooksuk** [comment]
I think that's all the Vagrant files were used for anyway.

**Comment by radum** [comment]
Yep pretty much :grinning:

**Pull request merged**
