### PR TITLE
Use APC cache for Docker and fix bug with changing component sort order

### LINKED ISSUE #594: 500 error when trying to authenticate in Dockerized version of Cachet
I'm trying to run Cachet with Docker and PostgreSQL. I already submitted 2 fixes to make this work, but as long as they're not merged into master I'm using our fork at https://github.com/experty/Cachet, and building the L5 branch at https://registry.hub.docker.com/u/experty/cachet/builds_history/183129/.

Well, so far so good, I'm able to bootstrap and setup the app now. 
```
docker run --name cachet-db -d postgres:9.4

docker run --rm --link cachet-db:db postgres:9.4 \
    sh -c 'exec psql -h db -U postgres -c "CREATE DATABASE cachet;"'

docker run --rm \
    --link cachet-db:db \
    -e DB_HOST=db -e DB_DRIVER=pgsql \
    -e DB_DATABASE=cachet -e DB_USERNAME=postgres -e DB_PASSWORD=  \
    experty/cachet:latest php artisan migrate --force

docker run --name cachet -d \
    --link cachet-db:db \
    -e DB_HOST=db -e DB_DRIVER=pgsql \
    -p 80:8000 \
    -e DB_DATABASE=cachet -e DB_USERNAME=postgres -e DB_PASSWORD=  \
    experty/cachet:latest
```
Now when I visit the server, I get the nice setup page. After configuring stuff, I arrive at the dashboard as I should and everything seems to work. The problem however, is that when I log out and then try to log in again, I get a 500 internal server error. There seems to be a problem with some Throttling library using the wrong Cache implementation. I looked at logs in the container, and found this error:
```
root@status:~# cat laravel-2015-04-20.log
[2015-04-20 16:18:38] production.ERROR: exception 'Illuminate\Session\TokenMismatchException' in /var/www/html/vendor/compiled.php:2486
Stack trace:
#0 /var/www/html/app/Http/Middleware/VerifyCsrfToken.php(29): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#1 /var/www/html/vendor/compiled.php(9019): CachetHQ\Cachet\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#2 /var/www/html/app/Http/Middleware/RedirectIfAuthenticated.php(51): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#3 /var/www/html/vendor/compiled.php(9019): CachetHQ\Cachet\Http\Middleware\RedirectIfAuthenticated->handle(Object(Illuminate\Http\Request), Object(Closure))
#4 /var/www/html/app/Http/Middleware/HasSetting.php(46): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#5 /var/www/html/vendor/compiled.php(9019): CachetHQ\Cachet\Http\Middleware\HasSetting->handle(Object(Illuminate\Http\Request), Object(Closure))
#6 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#7 /var/www/html/vendor/compiled.php(9010): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#8 /var/www/html/vendor/compiled.php(7017): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#9 /var/www/html/vendor/compiled.php(7006): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#10 /var/www/html/vendor/compiled.php(6991): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#11 /var/www/html/vendor/compiled.php(1981): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#12 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#13 /var/www/html/vendor/compiled.php(9027): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 /var/www/html/vendor/compiled.php(12171): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 /var/www/html/vendor/compiled.php(9019): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 /var/www/html/vendor/compiled.php(10873): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 /var/www/html/vendor/compiled.php(9019): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 /var/www/html/vendor/compiled.php(11877): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 /var/www/html/vendor/compiled.php(9019): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /var/www/html/vendor/compiled.php(11826): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 /var/www/html/vendor/compiled.php(9019): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /var/www/html/vendor/compiled.php(2524): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /var/www/html/vendor/compiled.php(9019): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(47): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /var/www/html/vendor/compiled.php(9019): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /var/www/html/vendor/compiled.php(9010): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#28 /var/www/html/vendor/compiled.php(1937): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#29 /var/www/html/vendor/compiled.php(1924): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#30 /var/www/html/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#31 {main}  
[2015-04-20 16:18:51] production.ERROR: exception 'ErrorException' with message 'call_user_func_array() expects parameter 1 to be a valid callback, class 'Illuminate\Cache\FileStore' does not have a method 'tags'' in /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/Repository.php:366
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'call_user_func_...', '/var/www/html/v...', 366, Array)
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(366): call_user_func_array(Array, Array)
#2 /var/www/html/vendor/graham-campbell/throttle/src/Factories/CacheFactory.php(53): Illuminate\Cache\Repository->__call('tags', Array)
#3 /var/www/html/vendor/graham-campbell/throttle/src/Factories/CacheFactory.php(53): Illuminate\Cache\Repository->tags('throttle', '217.123.240.93')
#4 /var/www/html/vendor/graham-campbell/throttle/src/Throttle.php(73): GrahamCampbell\Throttle\Factories\CacheFactory->make(Object(GrahamCampbell\Throttle\Data))
#5 [internal function]: GrahamCampbell\Throttle\Throttle->get(Object(Illuminate\Http\Request), 10, 10)
#6 /var/www/html/vendor/graham-campbell/throttle/src/Throttle.php(111): call_user_func_array(Array, Array)
#7 /var/www/html/vendor/compiled.php(5364): GrahamCampbell\Throttle\Throttle->__call('check', Array)
#8 /var/www/html/vendor/compiled.php(5364): GrahamCampbell\Throttle\Throttle->check(Object(Illuminate\Http\Request), 10, 10)
#9 /var/www/html/app/Http/Middleware/LoginThrottling.php(38): Illuminate\Support\Facades\Facade::__callStatic('check', Array)
#10 /var/www/html/app/Http/Middleware/LoginThrottling.php(38): GrahamCampbell\Throttle\Facades\Throttle::check(Object(Illuminate\Http\Request), 10, 10)
#11 /var/www/html/vendor/compiled.php(9019): CachetHQ\Cachet\Http\Middleware\LoginThrottling->handle(Object(Illuminate\Http\Request), Object(Closure))
#12 /var/www/html/vendor/compiled.php(2484): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /var/www/html/app/Http/Middleware/VerifyCsrfToken.php(29): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#14 /var/www/html/vendor/compiled.php(9019): CachetHQ\Cachet\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#15 /var/www/html/app/Http/Middleware/RedirectIfAuthenticated.php(51): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 /var/www/html/vendor/compiled.php(9019): CachetHQ\Cachet\Http\Middleware\RedirectIfAuthenticated->handle(Object(Illuminate\Http\Request), Object(Closure))
#17 /var/www/html/app/Http/Middleware/HasSetting.php(46): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 /var/www/html/vendor/compiled.php(9019): CachetHQ\Cachet\Http\Middleware\HasSetting->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /var/www/html/vendor/compiled.php(9010): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#21 /var/www/html/vendor/compiled.php(7017): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#22 /var/www/html/vendor/compiled.php(7006): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#23 /var/www/html/vendor/compiled.php(6991): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#24 /var/www/html/vendor/compiled.php(1981): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#25 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#26 /var/www/html/vendor/compiled.php(9027): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#27 /var/www/html/vendor/compiled.php(12171): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /var/www/html/vendor/compiled.php(9019): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /var/www/html/vendor/compiled.php(10873): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /var/www/html/vendor/compiled.php(9019): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /var/www/html/vendor/compiled.php(11877): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /var/www/html/vendor/compiled.php(9019): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /var/www/html/vendor/compiled.php(11826): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/html/vendor/compiled.php(9019): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /var/www/html/vendor/compiled.php(2524): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /var/www/html/vendor/compiled.php(9019): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(47): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /var/www/html/vendor/compiled.php(9019): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /var/www/html/vendor/compiled.php(9010): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#41 /var/www/html/vendor/compiled.php(1937): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#42 /var/www/html/vendor/compiled.php(1924): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#43 /var/www/html/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#44 {main}  
```
A little googling gets me at this issue: https://github.com/GrahamCampbell/Laravel-Throttle/issues/13

It seems that Cachet is using the wrong Cache implementation, but I don't really know what the right way to fix it is, or whether I'm doing something wrong.

By the way, I'm sure the credentials I'm using are correct, since I tried this whole process about 3 times to double check.

Please help :(

### PR DESCRIPTION
**Pull request by EdeMeijer**
By default, the file cache is used, but this breaks the throttling detection when authenticating. The APC cache is tagged and will allow you to log in again after installation.

Fixes #594

Accidentally also pushed fix for reordering components not working when you have deleted components.

### CODE REVIEW

**Comment by EdeMeijer** [comment]
Oh man, I forgot I had this pull request still pending and also pushed a fix for changing component sort orders. Well, maybe you can have a look at it? It's quite a nasty bug, so you probably want it fixed.

**Comment by jbrooksuk** [comment]
Can you squash please?

**Comment by EdeMeijer** [comment]
Done

**Comment by jbrooksuk** [comment]
@joecohens can you look at this and merge if you're happy please?

**Comment by joecohens** [comment]
@jbrooksuk Done :)

**Pull request merged**
