### PR TITLE
Dynamic language list within setup.

### LINKED ISSUE #366: make language-chooser dynamic
It would be nice if new translation would be available wihtout [further interventions](https://github.com/cachethq/Cachet/pull/365) as soon as there is a directory in app/lang/.

This also includes that the languages' name have to be included in the lang-files.

### PR DESCRIPTION
**Pull request by jbrooksuk**
Closes #366.

Nice and easy really. It does mean that we need PECL intl >= 1.0.0 though. Thoughts?

### CODE REVIEW

**Comment by joecohens** [comment]
:+1:

**Comment by joecohens** [comment]
We have a problem here, `locale_get_display_name` can only be used if you have the PECL intl extension installed so it should be required or find another way to get the locale name.

**Comment by joecohens** [comment]
Sorry I didn't saw the PR comment it's too late haha :). Maybe we can set a config file with the array mapping, how often are you going to install a new lang once they are done, instead of requiring a hole extension for such a small feature. Thoughts?

**Comment by jbrooksuk** [comment]
Without having a big array somewhere it's really only that function. We could add it to require within composer.json though.

**Comment by jbrooksuk** [comment]
Heh, I missed your second comment.

I guess for adding one language the dynamic language functionality is a bit overkill. Sure, it's a pain, but it's a one-time job.

**Comment by joecohens** [comment]
Haha happens :). Yeah I think it's better than requiring another PHP just for that.

**Comment by jbrooksuk** [comment]
Ok, lets do that then.

**Comment by joecohens** [comment]
Sure! I'm sending a PR to update the SP of config right now, I'll include it there :)

**Comment by jbrooksuk** [comment]
Awesome, sounds good to me!

**Pull request merged**
