### PR TITLE
Enhance settings performance queries

### PR DESCRIPTION
**Pull request by joecohens**
Changed the way we get Settings by using a service to query only once the settings a cache them to a variable so each time we call Setting::get('app_domain') and Setting::get('app_url') we only query the DB once. Little performance boost :)

// cc @cachethq/owners

### CODE REVIEW

**Comment by jbrooksuk** [comment]
This is a good idea! A lot of the settings will likely not change. Is it worth throwing them into apcu whilst we're at it?

**Comment by jbrooksuk** [comment]
Ready to merge?

**Comment by joecohens** [comment]
Just rebased should we merge?

**Comment by jbrooksuk** [comment]
I'm happy :)

**Comment by GrahamCampbell** [comment]
This is a misuse of a service class imo. This would be good for a "caching repository" or something.

**Comment by jbrooksuk** [comment]
Is it work merging now, to rewrite as a repository?

**Comment by GrahamCampbell** [comment]
That said, for now, we could just rename it to something else given that repositories are overkill.

**Comment by GrahamCampbell** [comment]
IE, this class is badly named, rather than actually needs rewriting.

**Comment by joecohens** [comment]
Yeah I can move it to the Repos folder

**Comment by GrahamCampbell** [comment]
We can call it "ConfigRepository". The code doesn't need to change. Don't move it to the repositories namespace please.

**Comment by GrahamCampbell** [comment]
We don't need to huddle all the repositories on one place and try to make them the same. That's not really the idea of repositories. NB, laravel's internal config implementation uses a "config repository".

**Comment by joecohens** [comment]
Should I leave it on the Services folder?

**Comment by GrahamCampbell** [comment]
We don't really need a services namespace. Hmmm...

**Comment by GrahamCampbell** [comment]
Maybe create a "Config" namespace. And simply call the class "Repository"?

**Comment by joecohens** [comment]
That sounds good

**Comment by GrahamCampbell** [comment]
We can still alias it as "Setting" in the global aliases if you like. :)

**Comment by joecohens** [comment]
Yeah I think it makes the difference between Laravel "Config" and app settings

**Comment by joecohens** [comment]
I rebased this and apply a StyleCI patch on Proxies list :), this is ready to merge.

**Comment by jbrooksuk** [comment]
I'm happy :) merge!

**Pull request merged**
