### PR TITLE
Fix for: Click on "manage subscription" causes "invalid signature"

### PR DESCRIPTION
**Pull request by langemeijer**
This fixes issue: https://github.com/CachetHQ/Cachet/issues/4013

### CODE REVIEW

**Comment by vikramarsid** [comment]
@langemeijer I still see the issue, ManageSubscription links cause 
Error 403
Invalid signature.
Forbidden

URL is missing signature params

`https://example.com/subscribe/manage/mEwLTdnSmkkj2D4FUYhSC8K4sdQY2xUBXwLXjmGLLH`

Requires signature:
`https://example.com/subscribe/manage/mEwLTdnSmkkj2D4FUYhSC8K4sdQY2xUBXwLXjmGLLH/signature=<signature>`

Even after adding the signature, we see the same issue.
This issue is related to #3714

**Comment by langemeijer** [comment]
Please be specific. You now have Cachet generating URLs with a signature? And when visiting this URL, Cachet throws an exception saying that the URL is invalid?

**Comment by mattluchterhand** [comment]
I am experiencing the same issue.  When a user first subscribes both the Verify  and Manage subscriptions buttons/links function properly.  Those links look similar to the following:
https://mystatussite.cachet.com/subscribe/manage/SUBSCRIBERKEY?signature=SIGNATUREKEY

When the subscriber receives component updates the Unsubscribe link at the bottom works as expected.  The Manage Subscription link, however, returns the Error 403 Invalid Signature message.  The link looks like this:
https://mystatussite.cachet.com/subscribe/manage/SUBSCRIBERKEY
I am guessing the issue is the missing ?signature=SIGNATUREKEY 

Let me know what other specifics you may need to track down the issue.

**Comment by SebastienFourreau** [comment]
HI there !

Can someone merge this?

Thanks

**Comment by SebastienFourreau** [comment]
I confirm that this fix works, thanks @langemeijer

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.

**Pull request closed without merging**
