### PR TITLE
Upgrade to Chart.js 2.0-beta2

### PR DESCRIPTION
**Pull request by fabian**
Picked up https://github.com/CachetHQ/Cachet/pull/1617 and fixed the tooltip problem.

Will also fix https://github.com/CachetHQ/Cachet/issues/1614.

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Awesome, thank you!

**Comment by GrahamCampbell** [comment]
This has broken the animations.

**Comment by GrahamCampbell** [comment]
Also, the tooltips are really hard to get to show up unless you make a real effort with the mouse.

**Comment by fabian** [comment]
Okay, will see if that can be fixed.

**Comment by fabian** [comment]
I was able to improve the tooltips by increasing the hit radius, will send a PR.

@GrahamCampbell which animations do you refer to?

**Comment by GrahamCampbell** [comment]
what we had before?

**Comment by fabian** [comment]
I can see an animation in the rendering of the chart, the lines "grow" from the bottom. However that animation works for me both before and after this PR.

Before: 71d6e692eb4aa2a4e838fcef2008006c0f839e69

After: 
ffa1fdbf1aa319ed66cc89e5c3e463217de53e6d

If you are referring to another animation please describe the element the animation is happening on and what it does.

**Comment by GrahamCampbell** [comment]
https://demo.cachethq.io/.

**Comment by jbrooksuk** [comment]
The demo just seems laggy?

**Comment by fabian** [comment]
Actually I just noticed it seems to be a browser problem. It works for me in Safari but not in Chrome and Firefox.

Even weirder when I set `responsiveAnimationDuration: 1000` it works in all browsers. The default value is 0 so it never should have worked in Safari. Probably a bug in Chart.js. Will send a PR with the new `responsiveAnimationDuration` value.

**Comment by jbrooksuk** [comment]
:+1:

**Pull request merged**
