### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by jbrooksuk**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Your cache is still stale?

**Comment by GrahamCampbell** [comment]
The autopresenter version will be without the `v` if it's not stale.

**Comment by GrahamCampbell** [comment]
Did you delete the vendor folder and lock file first? Composer uses them as a cache too.

**Comment by jbrooksuk** [comment]
I cleared the cache. Odd.

**Comment by jbrooksuk** [comment]
Ah I didn't remove `composer.lock`.

**Comment by GrahamCampbell** [comment]
And `vendor`.

**Pull request closed without merging**
