### PR TITLE
Banner can now be removed

### LINKED ISSUE #168: Banner should be unset
We should have a button to remove banner in case of not wanting to have one.

### PR DESCRIPTION
**Pull request by Jamesking56**
This may need a bit of cleaning to be more inline with your project but I hope this is alright. Fixes #168

### CODE REVIEW

**Comment by Jamesking56** [comment]
Don't know how to pass StyleCI...

**Comment by GrahamCampbell** [comment]
https://styleci.grahamjcampbell.co.uk/commits/b9c6bbaf81a579d12c4cca243ae49c166d76c919/diff

**Comment by GrahamCampbell** [comment]
Just add `/diff` to the url. StyleCI is still wip. :)

**Comment by GrahamCampbell** [comment]
Please squash to one commit.

**Comment by jbrooksuk** [comment]
@Jamesking56 if you squash down, we'll get it merged :+1:

**Comment by GrahamCampbell** [comment]
Or I could just fix the conflicts, squash, and merge. :)

**Comment by jbrooksuk** [comment]
Ok, do that :P

**Comment by GrahamCampbell** [comment]
Merged. Thanks @Jamesking56.

**Pull request closed without merging**
