### PR TITLE
Use warning rather than error

### PR DESCRIPTION
**Pull request by jbrooksuk**
image

Red is quite serious, maybe we could make it yellow? Also it matches the favicon when there is an issue.

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Ping @cachethq/owners.

**Comment by GrahamCampbell** [comment]
Maybe `info` instead?

**Comment by GrahamCampbell** [comment]
I think yellow looks strange.

**Comment by jbrooksuk** [comment]
Will try `info`.

**Comment by jbrooksuk** [comment]
image

Doesn't look bad.

**Comment by GrahamCampbell** [comment]
Yeh, I prefer that. :)

**Comment by jbrooksuk** [comment]
Me too, I'll update and merge. Feels better than a red block.

**Comment by joecohens** [comment]
:+1:

**Pull request merged**
