### PR TITLE
System last updated, enable/disable feeds and history

### PR DESCRIPTION
**Pull request by brendanbenke**
A few features features and that I developed for my employer based on their business requirements.  

FEATURES
- enable/disable RSS feeds  (this is already present for mail subscribers)
- enable/disable history (basically do not allow pagination outside the current window of incidents displayed on the timeline)
- ability to pick between Past Incidents and Incidents for the timeline header (the latter makes sense when history is not enabled)
- ability to show a last updated message next to the system status message (picks the most recently updated component to use with the time.  localized by default)

BUGS
- Bugfix: touch a component even when status is unchanged

TRANSLATIONS
- translations for all added features

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Wow! This is a lot of contributions.

We really need these to be separate PR's though I'm afraid. There are too many changes to merge in at once.

**Comment by brendanbenke** [comment]
Totally understandable.  I will break it up and resubmit.  Hope you guys
include it!

**Comment by jbrooksuk** [comment]
Thank you for doing this @brendanbenke however, I meant in separate Pull Requests. Sorry for not clarifying earlier.

**Comment by brendanbenke** [comment]
@jbrooksuk I totally understood ;-)  I just have not had the time to circle back on this.  I will try to pull the latest in the 2.4 upstream branch and merge everything then submit different PRs.

**Comment by dhileepbalaji** [comment]
any updates on this

**Comment by FalkW** [comment]
Would actually have been nice to accept this commit as some companies just want to show their status of the last 30 days without revealing a full history.

**Comment by cmardle** [comment]
"touch a component even when status is unchanged" - Would be great to see this included

**Comment by jbrooksuk** [comment]
@brendanbenke can we still look into separating these changes into individual PRs? There are many things which need rebasing and have changed since (i.e. no RSS feeds anymore).

Thanks!

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.

**Pull request closed without merging**
