### PR TITLE
Added previous helper

### PR DESCRIPTION
**Pull request by phecho**

### CODE REVIEW

**Comment by phecho** [comment]
User may enter the edit page for incident from statuspage

image

The cancel button shoud be back to where it come from.

**Comment by GrahamCampbell** [comment]
Why are all those parameters needed? We never intend to actually use it like that.

**Comment by GrahamCampbell** [comment]
Surely this would do:

```php
    /**
     * Create a new back url.
     *
     * @param string $route
     *
     * @return string
     */
    function previous($route)
    {
        $url = app('url');

        $previous = $url->previous()

        if ($url->full() === $previous) {
            return $url->route($route);
        }

        return $previous;
    }
```

**Comment by phecho** [comment]
@GrahamCampbell 
:+1:

**Comment by GrahamCampbell** [comment]
No. What I wrote was fine. Don't write code that we don't use.

**Comment by phecho** [comment]
@GrahamCampbell 

I think ** $route !== null ** is needed.

If use call previous(), obviously the route is null. then the statement of  ** $previous === $url->full() ** will not be executed, and the this statement takes more time.

Right?

**Comment by GrahamCampbell** [comment]
> I think $route !== null is needed.

No, it's not. Look at my code. I said that we don't allow passing `null`.

**Comment by phecho** [comment]
OK, thank you. I will change them.

**Comment by GrahamCampbell** [comment]
> The cancel button shoud be back to where it come from.

Honestly, I'm not convinced it actually should.

**Comment by GrahamCampbell** [comment]
I think I'm actually :-1: here.

**Comment by phecho** [comment]
@jbrooksuk 
What about you opnion?
Is it needed? if you give a :-1:  too. I will close this PR.

**Comment by jbrooksuk** [comment]
I'd much rather pressing back goes back to the dashboard.

**Pull request closed without merging**
