### PR TITLE
Fix L10n style and content

### PR DESCRIPTION
**Pull request by wfjsw**
Reviewed. Can also merge it to master if necessary.

### CODE REVIEW

**Comment by wfjsw** [comment]
Hmm... finding out what is happened there.
......seems removing heroku support also break the travis-ci

**Comment by jbrooksuk** [comment]
Don't worry about Travis, I'll fix it up.

**Comment by jbrooksuk** [comment]
Can you rebase? Looks like somethings gone wrong.

**Comment by wfjsw** [comment]
can you provide me a log or somethings else?
no problem at my side

**Comment by jbrooksuk** [comment]
I can't merge the commit, you'll need to pull down master, then rebase your branch again.

**Comment by GrahamCampbell** [comment]
@jbrooksuk You could just apply the styleci diff yourself to the L5 branch.

**Comment by GrahamCampbell** [comment]
styleci.io/commits/fa12463ac294a9782782b486d4cd3d3f5c4338f5

**Comment by GrahamCampbell** [comment]
https://styleci.io/commits/fa12463ac294a9782782b486d4cd3d3f5c4338f5

**Comment by GrahamCampbell** [comment]
That would be easier than rebasing.

**Comment by jbrooksuk** [comment]
Ok, I'll do that @GrahamCampbell :)

**Comment by jbrooksuk** [comment]
Done, thanks @GrahamCampbell and @wfjsw

**Comment by wfjsw** [comment]
Wait wait wait you are missing the most important part XDD
Resubmitted commit.

**Comment by jbrooksuk** [comment]
To where? :)

**Comment by wfjsw** [comment]
you have ignored L10n Part  :)
i have reseted it and now we can re-merge this pr now.

**Comment by jbrooksuk** [comment]
You'll need to re-open the PR I'm afraid.

**Comment by wfjsw** [comment]
OK

**Pull request closed without merging**
