### PR TITLE
added danish translation

### PR DESCRIPTION
**Pull request by mrbase**
This PR adds Danish translations to the project.

### CODE REVIEW

**Comment by mrbase** [comment]
The StyleCI should probably be addressed in the `en` files - I just copied the whole structure and translated the strings.

**Comment by GrahamCampbell** [comment]
Please rebase.

**Comment by mrbase** [comment]
Better ?

**Comment by jbrooksuk** [comment]
Thanks :+1:

**Comment by mrbase** [comment]
welcome :)

**Pull request merged**
