### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by GrahamCampbell**
1) Namespaced all controllers and moved them to the src folder
2) Removed hacky aliasing
3) Removed the workbench stuff - it just adds extra overhead we don't use

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Happy to merge?

**Comment by GrahamCampbell** [comment]
No.

**Comment by GrahamCampbell** [comment]
Not done yet.

**Comment by jbrooksuk** [comment]
Whoops, sorry.

Just merge when you're ready then.

**Comment by GrahamCampbell** [comment]
The upcoming changes I'm making will definitely need testing first. Anyway, going to get some lunch. Be back soon to finish this off...

**Comment by GrahamCampbell** [comment]
@jbrooksuk How does this look now?

**Comment by jbrooksuk** [comment]
Will check out now.

**Comment by GrahamCampbell** [comment]
:beers:

**Comment by jbrooksuk** [comment]
`Class SetupController does not exist`.

**Comment by GrahamCampbell** [comment]
Ooops. One sec...

**Comment by GrahamCampbell** [comment]
How about now?

**Comment by GrahamCampbell** [comment]
How about now?

**Comment by jbrooksuk** [comment]
Yep, looking good.

**Comment by GrahamCampbell** [comment]
k

**Pull request merged**
