### PR TITLE
Invite system for users

### PR DESCRIPTION
**Pull request by joecohens**
/cc @cachethq/owners 

Closes https://github.com/cachethq/Cachet/issues/320

### CODE REVIEW

**Comment by jbrooksuk** [comment]
@joecohens do you know what's left for this? I may finish it off over the next couple of days ready for V2.

**Comment by GrahamCampbell** [comment]
Unless we just do this for 2.0.

**Comment by GrahamCampbell** [comment]
I think we should focus on fixing bugs at this point.

**Comment by jbrooksuk** [comment]
I'm planning on getting as much as I can in to V2, since I can spend a day writing the docs for everything then.

**Comment by joecohens** [comment]
This is missing the translations, the email text to send and the signup page to accept the invite.

**Comment by jbrooksuk** [comment]
Ok, I'll see if I have enough time to finish this off on Saturday or something, unless you're able to get it done first :smile:

**Comment by joecohens** [comment]
@jbrooksuk Now we are just missing the translations strings and the email content :)

**Comment by jbrooksuk** [comment]
> @jbrooksuk Now we are just missing the translations strings and the email content :)

Make it basic for now? I need to update CrowdIn soon.

**Comment by GrahamCampbell** [comment]
Should we move this back to the 2.0 milestone now due to the fact that v2.0.0's release has been pushed back till next weekend?

**Comment by joecohens** [comment]
I think we could :)

**Comment by joecohens** [comment]
@cachethq/owners This is done :) can you take a look?

**Comment by jbrooksuk** [comment]
Checking this out now.

**Pull request merged**
