### PR TITLE
Fixes 319 - MySQL 5.6 compatibility

### PR DESCRIPTION
**Pull request by wdalmut**
Removed the default field during migrations for text fields - Issue #319

### CODE REVIEW

**Comment by jbrooksuk** [comment]
If you run this migration, then try and add an incident without a message, what happens?

**Comment by wdalmut** [comment]
It reply with that the message is a mandatory field.

```
Whoops. Something went wrong with the incident. {"message":["The message field is required."]}
```

add an incident dashboard cachet

**Comment by jbrooksuk** [comment]
And if you do a component without a description?

**Comment by jbrooksuk** [comment]
@wdalmut rather than making the fields required, you can make use of the `$attribute` property within the models, see [here](https://github.com/cachethq/Cachet/blob/master/src/Models/Component.php#L63) for existing attributes.

You'd need to add all of the fields for where you've removed the `default` value from.

**Comment by wdalmut** [comment]
Components allows also empty description.

**Comment by jbrooksuk** [comment]
Ok, so long as nothing has broken, then it should be ok. This will only work for newer installations mind.

**Comment by wdalmut** [comment]
:+1:

**Comment by wdalmut** [comment]
I have squashed my commits

**Comment by jbrooksuk** [comment]
Thanks mate.

**Comment by GrahamCampbell** [comment]
Also, our messages aren't too helpful. The end user should not be seeing json, lol.

**Comment by joecohens** [comment]
Lol yeah that's a thing we must be fixing :)

**Comment by jbrooksuk** [comment]
Yeah, I keep meaning to make the error messages apply to the input that is a problem.

**Comment by joecohens** [comment]
Maybe stop using the Session to display the errors and use Laravel $errors with a partial?

**Comment by jbrooksuk** [comment]
Create an issue :)

**Pull request merged**
