### PR TITLE
Catch invalid validation on api requests

### PR DESCRIPTION
**Pull request by joecohens**
// cc @jbrooksuk What do you think?

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
It would be better to do this using a try catch in a middleware imo.

**Comment by jbrooksuk** [comment]
@GrahamCampbell any suggestions on how that'd work?

**Comment by joecohens** [comment]
@GrahamCampbell Lol no middlewares on L4 yet but you are right might be better on a global catch or filter

**Comment by GrahamCampbell** [comment]
> Lol no middlewares on L4

No, L4 does have middlewares. :)

**Pull request closed without merging**
