### PR TITLE
Fix [object object] notification error with js

### PR DESCRIPTION
**Pull request by joecohens**
Closes https://github.com/CachetHQ/Cachet/issues/1486

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
> 100644 → 100755

:crying_cat_face:

**Comment by joecohens** [comment]
That's odd, I'll change them now

**Comment by jbrooksuk** [comment]
Hate it when that happens, but you can set Git to ignore file permission changes I believe.

**Comment by joecohens** [comment]
Do you know if setting the filemode = false will stop this?

**Comment by jbrooksuk** [comment]
I believe so :)

**Comment by joecohens** [comment]
:)

**Pull request merged**
