### PR TITLE
upgraded google2fa (0.7->5.0)

### PR DESCRIPTION
**Pull request by mxss**
#3378

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Hey, thanks for opening this @mxss. I'm unsure how I feel about requiring Imagemagick to be installed as well. 

Is there an alternative?

**Comment by mxss** [comment]
@jbrooksuk in recent versions of used package (pragmarx/google2fa) image generation is disabled that why I had to install additional package Bacon/QRCode which requires imagick

You can check package readme for more details:
https://github.com/antonioribeiro/google2fa

there's a few alternatives to that package but I'm not sure yet if we can get rid of imagick, I'll take a look

**Comment by jbrooksuk** [comment]
Thanks @mxss!

GD is much easier to install and is typical of most installations that I've come across, whereas I find Imagemagick less common.

**Comment by jbrooksuk** [comment]
It looks like https://github.com/chillerlan/php-qrcode has SVG support and doesn't list GD or Imagemagick as a requirement in `composer.json`.

**Comment by mxss** [comment]
@jbrooksuk done

**Comment by jbrooksuk** [comment]
Nice! Could you rebase this please and we'll merge it in?

**Pull request merged**
