### PR TITLE
RSS v2

### PR DESCRIPTION
**Pull request by jbrooksuk**
This re-introduces RSS to Cachet. The `spatie/feed` package allows us to setup individual feeds too, which is very nice.

### CODE REVIEW

**Comment by till** [comment]
@jbrooksuk any news on this? :)

**Comment by dbluxo** [comment]
🎆 🍾  Awesome! I missed RSS in actual version 2.4-dev

**Comment by ryanmcafee** [comment]
Any update on this?

**Comment by hamelsveld** [comment]
Any indication when the RSS feed will be back

**Comment by trueshanti** [comment]
How to properly implement the feed ?

**Comment by ghost** [comment]
Any update on the RSS feed please?

**Comment by ChrisTG742** [comment]
*bump* any progress on this issue? :)

**Pull request closed without merging**
