### PR TITLE
Cleaned up routes

### PR DESCRIPTION
**Pull request by jbrooksuk**
Basically naming most of the routes so that we can easily do #867.

### CODE REVIEW

**Comment by jbrooksuk** [comment]
@joecohens can you check this please before merge. I think at least every `GET` route (not including the API) is now aliased.

**Comment by GrahamCampbell** [comment]
This needs rebasing.

**Comment by jbrooksuk** [comment]
Done.

**Comment by joecohens** [comment]
@jbrooksuk It seems very good to me :) :+1:

**Comment by jbrooksuk** [comment]
Yay! Now we can sort out #867

**Pull request merged**
