### PR TITLE
Fix how tags are created

### LINKED ISSUE #3004: Should Component/tag be a ManyToMany relation?
**Affected feature** : Components (create and update at least)
**How to reproduce**:
- Go to `/dashboard/components/create`
- Fill the form
- Submit

**Exception thrown**: `BadMethodCallException: Call to undefined method Illuminate\Database\Query\Builder::sync()`.
**Note**: The operation is done on a fresh install and a fresh database. The component is successfully created but the exception is thrown when calling calling `$component->tags()->sync()`

The main problem is in ComponentController:210, the `sync()` method is declared only for the ManyToMany relations.
It seems Component and Tag are used as if they had a ManyToMany relation, but they are not declared like so. Also, there is no table `component_tag`.

Cachet version: 2.4 (3c51e5115a187c063efbc7a2e1167fa579b01aa0)
PHP 7.2.3

Please see the full log:
```
[2018-04-09 17:49:31] development.ERROR: BadMethodCallException: Call to undefined method Illuminate\Database\Query\Builder::sync() in /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2445
Stack trace:
#0 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1254): Illuminate\Database\Query\Builder->__call('sync', Array)
#1 [internal function]: Illuminate\Database\Eloquent\Builder->__call('sync', Array)
#2 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php(356): call_user_func_array(Array, Array)
#3 /home/anthony/public_html/Cachet-test/app/Http/Controllers/Dashboard/ComponentController.php(210): Illuminate\Database\Eloquent\Relations\Relation->__call('sync', Array)
#4 [internal function]: CachetHQ\Cachet\Http\Controllers\Dashboard\ComponentController->createComponentAction()
#5 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#6 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('createComponent...', Array)
#7 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(CachetHQ\Cachet\Http\Controllers\Dashboard\ComponentController), 'createComponent...')
#8 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Routing/Route.php(160): Illuminate\Routing\Route->runController()
#9 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(572): Illuminate\Routing\Route->run()
#10 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#11 /home/anthony/public_html/Cachet-test/app/Http/Middleware/Authenticate.php(61): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): CachetHQ\Cachet\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#13 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(65): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(574): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#34 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(533): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#35 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(511): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#36 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#37 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#38 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /home/anthony/public_html/Cachet-test/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#42 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#45 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#46 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#47 /home/anthony/public_html/Cachet-test/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#48 {main} {"identification":{"id":"5e7be334-f568-4749-966b-ff9d5739d24f"}}
```

### PR DESCRIPTION
**Pull request by jbrooksuk**
Fixes #3004

---

We now have commands that create, delete, update and apply tags. This fixes the issue where `sync` is not available on a `ManyToMany` relation.

### CODE REVIEW

**Comment by anthonybocci** [comment]
When I test I have the following error: `include(/Applications/MAMP/htdocs/Cachet/vendor/composer/../../app/Foundation/Providers/ModuleServiceProvider.php): failed to open stream: No such file or directory`.

It seems this file has been removed from 2.4 too.

**Comment by jbrooksuk** [comment]
You need to run `rm -rf bootstrap/cache{,t}/*`.

**Comment by anthonybocci** [comment]
Indeed, manually removing cache worked. This PR worked for me!

**Comment by shuichiro-makigaki** [comment]
Works on my side.

**Pull request merged**
