### PR TITLE
Twigbridge fixes

### LINKED ISSUE #1437: Twig doesn't work
i use twig in my incident templates but it doesn't work. It output only the twig code
e.g.`{% if {{ app.request.get('trackDomain') }} == 'test.webtrekk.com'|url_encode %}
 Das ist ein Test
{% endif %}`

I'm on HEAD e33f794. i tested it also with deee3b7. It doesn't work. Is there anything i have to do? Config? Shortcut before the twig code start?

### LINKED ISSUE #1445: Broken twig bridge config
image

That debug config clearly won't work. You can't read the config before it's been filled.

### PR DESCRIPTION
**Pull request by jbrooksuk**
Fixes #1437, fixes #1445

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Ballsed up the commit message, but whatever.

**Comment by Citrullin** [comment]
I'm on ab2ab5d . And the twig template doesn't work. Our Story we want to build with CachetHQ: We have different tracking servers etc. for our customers. With this template i want to filter the status updates .

**Comment by jbrooksuk** [comment]
If you're still using the Twig code from #1437 then it's invalid. I had to make some changes for it to work.

**Comment by Citrullin** [comment]
Ahh, okay. :)

**Pull request merged**
