### PR TITLE
No data available status

### PR DESCRIPTION
**Pull request by nicolasfagotti**
We added a new status for the components, "No Data Available". This doesn't seem meaningful for manual modifications, but when components are regularly updated through Cachet API, it's pretty useful to have it.

If it's not desirable, my apologies and just cancel the pull request :)

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Hmm, I like the idea of having an almost indeterminate status, but I don't know if I like the "No data available" status.

Actually, under what circumstances would you have no data?

**Comment by nixmomo** [comment]
Some monitorings use the "unkown" status if they can't get informations about the service health from the monitoring client. Nagios as example use it :-)

If you use cachet as a internal status Page it can be helpful to have it to see that something is going wrong. if you match it hard to "down" and the service isn't really down so you have a status between down and up.

**Comment by nicolasfagotti** [comment]
Well, for example, we query our component statuses not directly hitting the components but querying a central log application.

```Cachet -> log app <- components```

So, in our case, having no information in the logs doesn't mean anything about a component status. What we are looking for is a way to say that is not possible to define the status of the component.

**Comment by jbrooksuk** [comment]
Okay, thanks for providing a better explanation.

I think I prefer "Unknown". Thoughts? Ping @CachetHQ/core.

**Comment by nicolasfagotti** [comment]
Yes, it sounds better "Unknown".

**Comment by jbrooksuk** [comment]
Okay and two more points here:

1. Can you _only_ update the English translation, please? The reason is that we sync the English files up to CrowdIn, then they generate the files when needed. I'd have to go through every language and re-sync them. This makes it much easier for me to deal with :+1:
2. You'll need to update the `./app/Bus/Commands/Component` command files to validate a status of `0` too, as it's currently only allowing 1-4.

**Comment by nicolasfagotti** [comment]
If I'm not mistaken, the test that failed is not related to the changes on this branch.

**Comment by jbrooksuk** [comment]
Can you squash into one commit, please? We have a commit adding languages, then removing them. I'll check that this does everything we expect on Sunday :)

**Comment by nicolasfagotti** [comment]
Done.

Sorry about that. It's my first time with Cachet, Laravel, Github as issue tracker, etc. I hope my next pull request be cleaner :)

**Comment by jbrooksuk** [comment]
Can you rebase this please? We changed some stuff in the Laravel upgrade. Once debased we will merge this immediately.

**Comment by nicolasfagotti** [comment]
Done

**Pull request merged**
