### PR TITLE
Fixed ignoring files

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Github things this is a javascript project because of all the vendor files without this too. :/

**Comment by jbrooksuk** [comment]
I think the build stuff can stay, because we have no setup yet to recompile. The actual assets can be removed though.

**Comment by GrahamCampbell** [comment]
So what do you want to keep exactly?

**Comment by jbrooksuk** [comment]
Anything in `public` basically. The `app/assets/bower_components/*` can be ignored though.

**Comment by jbrooksuk** [comment]
They should be pulled down for development anyway.

**Comment by jbrooksuk** [comment]
You can still remove `bower_components`.

**Comment by GrahamCampbell** [comment]
Will just commit this to the master.

**Pull request closed without merging**
