### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Stage 1 of #188. This needs testing to make sure I didn't accidentally break anything, then I'll continue with the next stage.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
NB, the next stages involve namespacing the controllers/models/filters. This will make upgrading to laravel 5 easier, and also leave a better architecture without the possibility of class name collisions.

**Comment by jbrooksuk** [comment]
I'll test shortly - just working on re-ordering components.

**Comment by jbrooksuk** [comment]
Can you rebase, then I'll test.

**Comment by GrahamCampbell** [comment]
Sure...

**Comment by GrahamCampbell** [comment]
Done.

**Comment by jbrooksuk** [comment]
All seems to be working.

**Comment by GrahamCampbell** [comment]
Great. Can we merge this, and I'll continue the next step?

**Comment by jbrooksuk** [comment]
Yeah, go for it.

**Pull request merged**
