### PR TITLE
Incident form is now prefill with the originally data

### LINKED ISSUE #330: Incident form error should prefil the originally submitted data
If you submit an incident but leave off the status, an error is shown and all form fields are emptied.

### PR DESCRIPTION
**Pull request by Crash--**
Close #330

### CODE REVIEW

**Comment by jbrooksuk** [comment]
I think you could actually use `Input::old()` here.

**Comment by Crash--** [comment]
As we already store the previous $incident in the Session and we already do a check $incident->isValid() what will be the benefice of doing that with Input::old()? (it's really a question, not a sarcasm or something else)

**Comment by jbrooksuk** [comment]
Actually, we should be using `Binput::old` which is @GrahamCampbell's safe version of it.

What it does is use the `Session::flash` code to maintain the form content. We probably could just use `$incident` but I've always preferred that.

**Comment by jbrooksuk** [comment]
@joecohens is this an ok way of doing things?

@Crash-- this needs rebasing.

**Comment by joecohens** [comment]
I don't think so, this should be `Binput::old('incident.name', $incident->name)`

**Comment by jbrooksuk** [comment]
Thought so :)

**Comment by jbrooksuk** [comment]
@Crash-- can you rebase and use `Input::old` please (`Binput` isn't aliased, so that won't work).

**Comment by jbrooksuk** [comment]
Closed by c3e8993.

**Pull request closed without merging**
