### PR TITLE
Fix timezone error on metric point api.

### LINKED ISSUE #3794: Metrics - Not in timezone
Hello,

when you set time zone to your location (CEST for example) metrics are still shown in UTC. Could you change this, so all parts take the time zone as configured?

Best regards

### PR DESCRIPTION
**Pull request by Sevenn83**
It would fix #3794, #2459.

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Looks like the tests need updating.

**Comment by zanechua** [comment]
Can confirm that this fix does fix the timezone issue on the latest 2.4 branch (cfd173c).

* Set system timezone
* Set .env timezone
* Set timezone in app

**Comment by rpartapsing** [comment]
For me it crashed the metric section Leaving me with a "loading data" screen

**Comment by westej2** [comment]
these fixes worked for me.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.

**Pull request closed without merging**
