### PR TITLE
zh-Hant and zh-Hans Translation

### PR DESCRIPTION
**Pull request by applelam**
Translation for Chinese (Traditional) and Chinese (Simplified)

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Wow - thank you **so much** for these translations. This is incredible!

**Comment by wfjsw** [comment]
so.. you have already solve the messy fonts problem? seems great.

**Comment by jbrooksuk** [comment]
It could be the translations fixing this :) Let's close #447.

**Comment by wfjsw** [comment]
All right I am thinking about if fuzzy 'charset' make that happens...... I will check & fix that soon.

**Pull request merged**
