### PR TITLE
Test that the cachet:* commands work

### PR DESCRIPTION
**Pull request by jbrooksuk**
This tests that `cachet:seed` and `cachet:metrics` work.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Maybe make separate test methods for them?

**Comment by jbrooksuk** [comment]
I thought that, but figured they're overkill? I can do if you think it's a good idea though?

**Comment by GrahamCampbell** [comment]
I think it would be useful to keep that atomic, so we can see exactly what's broken if we mess up.

**Comment by jbrooksuk** [comment]
Sure, I'll do that.

**Comment by jbrooksuk** [comment]
Done!

**Comment by jbrooksuk** [comment]
Closing this, I'll just do it again.

**Pull request closed without merging**
