### PR TITLE
Add missing in important outline buttons

### PR DESCRIPTION
**Pull request by joecohens**
Fixes https://github.com/CachetHQ/Cachet/pull/1619#issuecomment-197222773

### CODE REVIEW

**Comment by jbrooksuk** [comment]
:+1:

**Comment by TheoBearman** [comment]
Still dosen't look fixed my side...

**Comment by joecohens** [comment]
We need to rebuild

**Comment by jbrooksuk** [comment]
Really need a bot for this.

**Comment by TheoBearman** [comment]
Yeah, we really do.

**Comment by TheoBearman** [comment]
I can confirm that this fix is working after the latest asset rebuild. Thanks @joecohens and @jbrooksuk.

**Comment by jbrooksuk** [comment]
:+1:

**Pull request merged**
