### PR TITLE
Translation update

### PR DESCRIPTION
**Pull request by foxted**
I checked the lang branch and saw a few things I could do something about so I did, let me know what you think about it: 

- [x] Fix missing translation after rebase
- [x] Add missing translation support for API, team & component group features
- [x] Add missing page titles translations
- [x] Change the add member page title markup to match the other "add pages"
- [x] Creation of the french translation folder with all the files and a proposed translation (which could be added on CrowdIn for validation I guess)

The following changes are about the views, they just made sense to me, but I could be wrong:

- [x] Moved the `dashboard/groups.blade.php` to `dashboard/components/groups/index.blade.php`
- [x] Moved the `dashboard/components/add-group.blade.php` to `dashboard/components/groups/add.blade.php`
- [x] Moved the `dashboard/incidents/incident-template.blade.php` to `dashboard/incidents/templates/index.blade.php`

That's all folks!

### CODE REVIEW

**Comment by jbrooksuk** [comment]
@GrahamCampbell does this conflict with #277?

**Comment by foxted** [comment]
I took the lang branch that @GrahamCampbell created as a starting point, so it shouldn't.

**Comment by jbrooksuk** [comment]
So #277 needs to be merged first?

**Comment by foxted** [comment]
I think you can also merge this one into the `lang` branch and then merge the `lang` branch into the `master` branch, but I guess @GrahamCampbell would know better :)

**Comment by foxted** [comment]
And there is still some work regarding the other locales.

**Comment by GrahamCampbell** [comment]
@jbrooksuk Not it doesn't conflict.

**Pull request merged**
