### PR TITLE
Patching manage subscription

### PR DESCRIPTION
**Pull request by AntonioKL**
Existing subscriber should be able to manage his setting without considering if someone is allowed to subscribe or not.

### CODE REVIEW

**Comment by jbrooksuk** [comment]
@AntonioKL do you know if https://github.com/CachetHQ/Cachet/pull/3431 superseded this on purpose?

**Comment by AntonioKL** [comment]
> @AntonioKL do you know if #3431 superseded this on purpose?

Can you please explain? Not sure what do you mean?

**Comment by jbrooksuk** [comment]
The linked PR has some of the same code as this branch?

**Comment by AntonioKL** [comment]
> The linked PR has some of the same code as this branch?

3431 is about GDRP , not sure how it is relevant for subscription management. 

This is my own code and I didn't take it from anybody.

**Comment by jbrooksuk** [comment]
>> The linked PR has some of the same code as this branch? ...

@AntonioKL sorry, I’m not suggesting you copied it, I was just wondering if there is overlap and the other PR addresses both issues? GDPR is closely related to subscriptions, you see.

**Comment by AntonioKL** [comment]
> > > The linked PR has some of the same code as this branch? ...
> 
> @AntonioKL sorry, I’m not suggesting you copied it, I was just wondering if there is overlap and the other PR addresses both issues? GDPR is closely related to subscriptions, you see.

Doesn't overlap.

**Comment by jbrooksuk** [comment]
🤔 I just checked again and it doesn't. Sorry, I'm not sure what I'd looked at yesterday.

Before this gets merged, we still need to change the middleware, please.

**Comment by jbrooksuk** [comment]
@AntonioKL ah, it's https://github.com/CachetHQ/Cachet/pull/3422 which has similar files.

**Comment by AntonioKL** [comment]
@jbrooksuk 
Please elaborate

**Pull request merged**
