### PR TITLE
Implement the system status api endpoint

### LINKED ISSUE #1936: API endpoint to get System Status
Can we get an endpoint that just gets the entire system status message.
For example, if all systems are operational the message the endpoint should return

```json
{
  "message": "All systems are operational"
}
```

### PR DESCRIPTION
**Pull request by jbrooksuk**
Closes #1936

---

Much ❤️ to @adammbalogh for his go at this.

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Ping @CachetHQ/owners.

**Comment by joecohens** [comment]
👍

**Comment by GrahamCampbell** [comment]
Not sure about putting it in integrations. That stuff should be reserved for external services imo.

**Comment by jbrooksuk** [comment]
> Not sure about putting it in integrations. That stuff should be reserved for external services in my opinion.

What would you go for? Services?

**Comment by GrahamCampbell** [comment]
Not sure. Give me 30 mins to think about it. Sorry I can't get on slack right now. My internet connection where I am right now is total shite.

**Comment by jbrooksuk** [comment]
Going with *Integrations* for now. We can always rename them 👍

**Pull request merged**
