### PR TITLE
Fix timezones presenting

### PR DESCRIPTION
**Pull request by joecohens**
Using Carbon again to query and fix presenters to use timezone. Needs confirmation.

Fixes https://github.com/cachethq/Cachet/issues/419

### CODE REVIEW

**Comment by jbrooksuk** [comment]
@joecohens you'll also probably want to remove the timezone setting in `LoadConfigServiceProvider` as we should remain at UTC.

**Comment by joecohens** [comment]
Not sure if it makes difference, let me check.

**Comment by jbrooksuk** [comment]
I think we should be keeping the timezone as UTC, but it's worth checking.

**Comment by joecohens** [comment]
I'm your right I don't think it's making the change since Laravel sets the default date time https://github.com/laravel/framework/blob/36487a19f399fbe246fd9170d4c2dba969307ae8/src/Illuminate/Foundation/start.php#L167 

So the override is not working at all :stuck_out_tongue_winking_eye:

**Comment by jbrooksuk** [comment]
Let's get this bad boy merged!

**Pull request merged**
