### PR TITLE
Shows incident updates on the status page.

### PR DESCRIPTION
**Pull request by uxen-ab**
Shows the full incident updates' messages on the status page without truncating. The goal is to see the incident and the incident updates on the same page, without clicking or reloading any page.

It's still possible to use markdown to use a kind of title or something like that with strong, but it allows us to see the full message and there is no need to load an other page to see the message.
Also, the date is displayed in a tooltip as it is for an incident.

cachet-pull-request-show-incident-updates

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Can you rebase on to `2.4` please as there some extra commits that don't need to be in there.

**Comment by uxen-ab** [comment]
I have executed `git rebase`, fixed the merge issues with the previous pull requests that were merged, and merged that with my branch.
Is this ok for you? If not explain me, I'll clean the branch or reapply only the commit.

**Comment by jbrooksuk** [comment]
Can you give me collaborator access so I can rebase? :)

**Comment by GrahamCampbell** [comment]
"P

**Comment by GrahamCampbell** [comment]
:P

**Comment by uxen-ab** [comment]
@jbrooksuk I've added you as collaborator of my repository :)
I'll just accept a pull request from Backstroke.

**Comment by jbrooksuk** [comment]
Can you rebase please :)

**Comment by uxen-ab** [comment]
Rebase done, I've fixed the conflicts :)

**Comment by jbrooksuk** [comment]
🙈 

This is mental. Your PR should only contain the changes _you've_ made.

**Comment by uxen-ab** [comment]
Indeed you're right, I think the problem comes from my rebasing and merging.
This PR takes more time to merge that the time I've spent to do it, I think the easier is to cancel this PR and reapplying my changes.

**Comment by jbrooksuk** [comment]
Would that be okay?

**Comment by uxen-ab** [comment]
Yes, I'll do that now.

**Pull request closed without merging**
