### PR TITLE
Use the application/vnd.api+json content-type header

### PR DESCRIPTION
**Pull request by jbrooksuk**
Ping @CachetHQ/owners.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Nah. I don't like this. GitHub don't do that, right?

**Comment by jbrooksuk** [comment]
According to http://jsonapi.org/recommendations/ it's the right thing to do?

**Comment by GrahamCampbell** [comment]
That spec doesn't seem widely adopted though, and technically, it itself doesn't comply with the HTTP spec.

**Comment by GrahamCampbell** [comment]
GitHub sets the content type to be application/json on their API, then has a special X-GitHub- header for the specific types/

**Comment by jbrooksuk** [comment]
That's enough for me to say don't worry.

**Pull request closed without merging**
