### PR TITLE
✨ Add cachet:install command

### PR DESCRIPTION
**Pull request by jbrooksuk**
This magic command should install Cachet for the user, by following the given commands.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
What about the app install command?

**Comment by jbrooksuk** [comment]
This does more of a setup than it does an installation, for people who don't want to use the setup screen.

**Comment by GrahamCampbell** [comment]
I was meaning should this command run the install command?

**Comment by jbrooksuk** [comment]
I don't think it can as we don't have any .env file settings.

**Comment by sso-ot** [comment]
May I ask how do you run this to automate the setup??  I have my server up and running and I see the file but i'm not sure how to actually run this command in the background to fill out all the info

**Pull request merged**
