### PR TITLE
Cleaned Up The Models And Repositories

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Note that this pull request doesn't actually namespace the models, just cleans them up.

### CODE REVIEW

**Comment by joecohens** [comment]
:+1: :+1:

**Comment by GrahamCampbell** [comment]
How does this look now?

NB, this will probably need to be actually tested given that I've enforced some extra type hinting in some of the models based on the phpdoc, and it's possible that phpdoc could have been incorrect.

**Comment by joecohens** [comment]
Looking good ! Have a question why string[] instead of array for php?

**Comment by jbrooksuk** [comment]
Array of strings?

**Comment by GrahamCampbell** [comment]
Yeh. We should always use more specific types instead of just `array` when possible.

For example, `Foo[]` is an array of Foo objects.

**Comment by joecohens** [comment]
I had never done that in PHP I like it!

**Pull request merged**
