### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by TheoBearman** [comment]
error

**Comment by GrahamCampbell** [comment]
Are you sure it was this commit?

**Comment by TheoBearman** [comment]
It was this PR because my install was fine after @jbrooksuk's commit yesterday.

**Comment by GrahamCampbell** [comment]
Oh, I see what the bug is. Your `.env` file has invalid syntax.

**Comment by GrahamCampbell** [comment]
Laravel was previously hiding that error.

**Comment by TheoBearman** [comment]
Well the contents of it are:

```
APP_ENV=local
APP_DEBUG=false
APP_URL=https://status.theobearman.com
APP_KEY=HIDDEN

DB_DRIVER=mysql
DB_HOST=localhost
DB_DATABASE=cachet
DB_USERNAME=cachet
DB_PASSWORD=HIDDEN

CACHE_DRIVER=apc

SESSION_DRIVER=apc
QUEUE_DRIVER=sync

MAIL_DRIVER=smtp
MAIL_HOST=smtp.zoho.com
MAIL_PORT=587
MAIL_USERNAME=status@theobearman.com
MAIL_PASSWORD=HIDDEN
MAIL_ADDRESS=status@theobearman.com
MAIL_NAME=TheoBearman.com System Status
```

What is invalid and what do I need to change it to?

**Comment by GrahamCampbell** [comment]
You're missing duple quotes on the last entry.

**Comment by GrahamCampbell** [comment]
Basically, previously, we were totally ignoring your .env file, and not giving any kind of error.

**Comment by TheoBearman** [comment]
Understood. Added the double quotes to `MAIL_NAME` and we're back up and running. Happy new year to you and your family.

**Comment by GrahamCampbell** [comment]
You too. ;)

**Comment by GrahamCampbell** [comment]
I'd recommend running `php artisan config:cache` too. It'll skip loading all the config and env data at runtime. You should see a decent performance improvement.

**Comment by TheoBearman** [comment]
Done. Thanks again!

**Comment by GrahamCampbell** [comment]
Once https://github.com/CachetHQ/Cachet/pull/1294 is fixed, it should actually run that command for users.

**Pull request merged**
