### PR TITLE
Incident view

### LINKED ISSUE #546: RSS feeds should link to the announcement
RSS feeds usually have items pointing to specific links. i think the RSS feeds produced by cachet should point to the announcement directly, or at least to the website.

### PR DESCRIPTION
**Pull request by jbrooksuk**
This adds a view for single incidents. Obviously right now this page doesn't do a lot expect for allowing a link directly to it, but it does allow us to immediately close #546 and then hopefully once merged I can do #547

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
> public/build/dist/js/all-d557ec2d69.js 100644 → 100755

This really needs to stop happening.

**Comment by GrahamCampbell** [comment]
What script are you running that's doing that?

**Comment by jbrooksuk** [comment]
`gulp`.

**Comment by jbrooksuk** [comment]
I'm sure I configured Git to ignore file permission changes.

**Pull request merged**
