### PR TITLE
Metric uptime (availability) percent calculation

### PR DESCRIPTION
**Pull request by Ranger-X**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
What about metrics that don't refer to uptime.

**Comment by GrahamCampbell** [comment]
For example, one of our own status pages: https://status.styleci.io/.

**Comment by Ranger-X** [comment]
You're right. Perhaps, I add an "Display metric uptime" checkbox to dashboard UI.

**Comment by jbrooksuk** [comment]
Have you got screenshots of this in action?

**Comment by Ranger-X** [comment]
Yeah, sure.
firefox_screenshot_2016-03-09t05-03-52 681z

**Comment by GrahamCampbell** [comment]
Not sure this actually makes sense?

**Comment by jbrooksuk** [comment]
> Not sure this actually makes sense?

Me neither.

**Comment by Ranger-X** [comment]
Ok. I close my PR?

**Comment by jbrooksuk** [comment]
Ping @joecohens, thoughts?

**Pull request closed without merging**
