### PR TITLE
Update logo to drop the HQ

### PR DESCRIPTION
**Pull request by jbrooksuk**
1. Less confusion
2. Actual product name
3. Consistent branding

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This image doesn't seem to be scaled correctly?

**Comment by jbrooksuk** [comment]
I've dropped the `cachet-sidebar-logo` in favour of the SVG remember, but yeah, something isn't right. @joecohens ??? :D

**Comment by GrahamCampbell** [comment]
@jbrooksuk I was meaning you literally need to change the size of the image.

**Comment by jbrooksuk** [comment]
Fixed now :)

**Comment by joecohens** [comment]
Better :)

**Comment by GrahamCampbell** [comment]
:+1:

**Pull request merged**
