### PR TITLE
[Proposal] Format routes

### PR DESCRIPTION
**Pull request by joecohens**
@cachethq/owners What do you think?

### CODE REVIEW

**Comment by jbrooksuk** [comment]
@joecohens @GrahamCampbell do we want to run the patch on this?

**Comment by GrahamCampbell** [comment]
https://styleci.grahamjcampbell.co.uk/commits/8850782896669986801cd97e7fa715a204d8760c/diff

**Comment by GrahamCampbell** [comment]
I've got no time, sorry.

**Comment by jbrooksuk** [comment]
I'll do it :)

**Comment by joecohens** [comment]
@jbrooksuk Thanks!

**Comment by jbrooksuk** [comment]
Oh, hang on, I'm not sure how to merge it into your fork.

**Comment by joecohens** [comment]
I think you can't :( if I just have to align the arrays I'll doit quickly.

**Comment by jbrooksuk** [comment]
Just apply the styleci patch, do you know how to get it?

**Comment by joecohens** [comment]
Noup I was going to has Graham haha can you explain me?

**Comment by jbrooksuk** [comment]
Sure.

1. Click on the StyleCI **Details** link: https://styleci.grahamjcampbell.co.uk/commits/8850782896669986801cd97e7fa715a204d8760c
2. Add `/diff` to the end of the URL.
3. Download the patch file somewhere (and remember).
4. In the Terminal (assuming you're on the branch) run `git apply patch.txt`
5. Add, commit, push.

Really easy :)

**Comment by joecohens** [comment]
Thanks! :)

**Comment by joecohens** [comment]
Ok @GrahamCampbell I'm in love with your StyleCI now!

**Comment by GrahamCampbell** [comment]
lol, i do plan to add an easier way to get to the diffs, and a pretty way to render them in the browser too

**Comment by jbrooksuk** [comment]
@GrahamCampbell please do, just a download button would be a good start ;)

**Comment by joecohens** [comment]
I was going to send you a PR with that right now :)

**Comment by GrahamCampbell** [comment]
> I was going to send you a PR with that right now :)

Awesome.

**Comment by jbrooksuk** [comment]
Everyone happy to merge now that it's fixed up.

**Pull request merged**
