### PR TITLE
Move HumanStatus to Presenter, see also #1258

### PR DESCRIPTION
**Pull request by phecho**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Cancelling travis for now. I'll ask you to rebase this 15 mins or so after I've fixed the travis speed issue.

**Comment by GrahamCampbell** [comment]
Please rebase. ;)

**Comment by phecho** [comment]
done

**Comment by jbrooksuk** [comment]
Tests are WAY faster, awesome work @GrahamCampbell!

**Comment by GrahamCampbell** [comment]
:star2:

**Pull request merged**
