### PR TITLE
Incident updates

### PR DESCRIPTION
**Pull request by jbrooksuk**
Part of #1176.

---

- [x] Ability to report incident updates.
- [x] Ability to delete incident updates.
- [x] Ability to edit incident updates.
- [x] API endpoints.
- [x] Status page design to accommodate the updates.
- [x] Improve single page designs where updates are available.
- [x] Improve seeder so that incidents are using updates.
- [ ] Improve dashboard design for reporting updates. (working on another PR)
- [x] Fix status page alert to account for updates.
- [ ] Write documentation for incident updates.

Something I forgot to push yesterday, incident updates are becoming a thing.

### CODE REVIEW

**Comment by jbrooksuk** [comment]
image

**Comment by TheoBearman** [comment]
Yayayayayayayay

**Comment by jbrooksuk** [comment]
Ping @joecohens for design work on this!

**Comment by jbrooksuk** [comment]
**Incident timeline:**

image

@joecohens I think we need to change this so that each incident is shown, with a timeline of updates beneath it. This is a pretty radical change, but so are Updates anyway...

**Single incident:**

image

This comes with some `github-markdown.css` overrides so that we have headers at the right size, proportionate to actual _design_ headers. I'm still not keen on this, but essentially the status page view would be more like this anyway.

**Comment by jbrooksuk** [comment]
The status page also needs to show the incident at its most up-to-date status too (I've added this to `IncidentPresenter` already. Just need to display it.

**Comment by jbrooksuk** [comment]
The status page will now show the most recent status for any incident with updates, which makes sense to me. If there are no updates, then the incident will follow the existing behaviour.

**Comment by jbrooksuk** [comment]
For the status page design I'm also thinking of splitting the timeline up, so that it shows an individual timeline for each incident followed by updates.

**Comment by jbrooksuk** [comment]
I think that Incident Updates need their own statuses too, or we need to change existing incident statuses to make more sense?

**Comment by jbrooksuk** [comment]
Current layout with updates:

image

**Comment by jbrooksuk** [comment]
I'm still not happy with the design of the status page, especially the single page.

**Comment by jbrooksuk** [comment]
Joe is going to finish off the dashboard and make some design changes to both the status page and the single pages.

**Comment by jbrooksuk** [comment]
Once this is done, I'll add the ability for incidents to affect multple components/groups.

**Comment by jbrooksuk** [comment]
I've rebased this entire branch to remove the asset compiling, and to drop some commits that weren't needed, so it'll merge easier now.

**Comment by joecohens** [comment]
@jbrooksuk Can we merge this I need it for the new design?

**Comment by jbrooksuk** [comment]
Yeah. I can finish it off afterwards.

**Pull request merged**
