### PR TITLE
Fixed german translation

### PR DESCRIPTION
**Pull request by PietsHost**
Fixed german translation and changed everything to courtesy form

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please send to our crowdin. :)

**Comment by PietsHost** [comment]
sorry, I don't know what you mean

**Comment by GrahamCampbell** [comment]
https://github.com/CachetHQ/Cachet/blob/2.4/CONTRIBUTING.md#languages

**Comment by GrahamCampbell** [comment]
:)

**Pull request closed without merging**
