### PR TITLE
[WIP] Custom Statuses

### LINKED ISSUE #2051: Add new component status for ongoing maintenance (e.g. UNDER MAINTENANCE)
During discussions in #2044 we came across the idea to add another status for components to be able to mark the component as "under maintenance". This would ease our maintenance workflow:
- Schedule a maintenance
- When maintenance is started set the status to "UNDER MAINTENANCE"
- When maintenance is done reset the status

We're also creating incidents via a checking service and so we are able to skip incident creation when the component is under maintenance.

### PR DESCRIPTION
**Pull request by jbrooksuk**
Closes #2051

---

Not a lot to see here yet. We're creating the `statuses` table and migrating existing statuses into said table.

Things to do:

- [ ] Think about whether we need to include an `order` column for each type?
- [ ] Migrate existing `incidents.status` data into new `statuses.id` value
- [ ] Drop existing `incidents.status` column
- [ ] Setup model relationships
- [ ] Update views to use new status value
- [ ] Update API

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Note that the status values will now **not** be backwards compatible, making this a v3.0 release when the time comes.

**Comment by joecohens** [comment]
Also doing this the statuses won't be translated automatically, are they?

**Comment by jbrooksuk** [comment]
Correct. It's a shame because auto translations were nice, but this offers far more benefits.

**Comment by jbrooksuk** [comment]
Unless we added `locale`...

**Comment by ConnorVG** [comment]
Or we can just key the statuses rather than giving them (in the db) full representations. That'll just pass to trans as we sort of do now. Easy win.

This has been a long time coming ❤️

**Comment by m1guelpf** [comment]
#~winter~statusesarecoming

**Comment by jbrooksuk** [comment]
@ConnorVG what do you mean?

**Comment by Geethree** [comment]
Any updates on this PR? This is the sole feature keeping us from using Catchet...

**Comment by jbrooksuk** [comment]
@Geethree not yet I'm sorry! Needs more time and thought :)

**Comment by Geethree** [comment]
Waiting.
Hoping.
Wishing.
For custom statuses!

**Comment by jbrooksuk** [comment]
I promise they'll get here, there's just a lot of stuff to do elsewhere that may change the way this works :)

**Comment by Geethree** [comment]
Meh. I just overwrote the appropriate lang resource and mounted that in the appropriate location as a docker volume. Perhaps that will work. /shrug

**Comment by jbrooksuk** [comment]
@Geethree that's really the easiest way to do this if you're comfortable changing Cachet source files 🌈

**Comment by JamesrenaudMitel** [comment]
Watching this PR, we had this on a previous system before moving to Cachet and would love to have the same functionality with Cachet

**Comment by jbrooksuk** [comment]
@JamesrenaudMitel cool. I will pick this up again at some point.

**Comment by Geethree** [comment]
Can it be picked up yet?

**Comment by Geethree** [comment]
Is there anyway I could help with this issue?

**Comment by jbrooksuk** [comment]
Note to self. Custom statuses in 3.x!

**Pull request closed without merging**
