### PR TITLE
Add component/group filter & historical status transitions

### PR DESCRIPTION
**Pull request by nicolasfagotti**
Hi! We are using the next branch for filtering the specific component/group information and also support the historical status transition information.

Features on this branch:
* Status page dropdown for allowing filtering components/groups.
* Separated pages showing information only related to the component/group filtered (status, metrics, incidents, etc.)
* Historical status transitions for components/groups. Each component/group status change is saved for showing these transitions on different kind of charts.

When a component/group is filtered, the status transition charts are displayed like in the next image:
status_transition_charts

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Wow, that looks nice!

I'll take a look at the implementation tomorrow :)

**Comment by nicolasfagotti** [comment]
We've been bugfixing the branch and updating a bit the implementation to make it simpler and more reliable.

If you have any questions, suggestions, or if it is better for checking the implementation to have separate branches for each feature, just let me know :)

**Comment by jbrooksuk** [comment]
Ping @joecohens on this, I reckon we merge the new design before this, then we can better accommodate it. Thoughts?

**Comment by GrahamCampbell** [comment]
Oh dear, lots of conflicting files. @CachetHQ/core We probably need to discuss what we want to do with this in January.

**Comment by GrahamCampbell** [comment]
It would be a shame for this work to go to waste.

**Comment by paulzehetmayr** [comment]
Hi Graham, 

Could you please elaborate on this? 

Thanks!
Paul

**Comment by GrahamCampbell** [comment]
Yeh, this PR is not current in a mergable state, because a lot has changed since it was originally worked on. After conflicts have been resolved, it also needs a review from the Cachet core team. All in all, a lot of work. The Cachet core team will meet in January to decide to proceed or not.

**Comment by nicolasfagotti** [comment]
At the same time, the changes in our implementation for supporting the historical transitions also changed a lot from what is presented here.

Because we thought the modifications were not so attractive to others (lack of feedback basically), we decided not to care that much on breaking compatibility with the Cachet evolution. But if you think it can be something useful for being included, it would be nice to evaluate the effort of putting our work in sync with the latest Cachet code.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.

**Pull request closed without merging**
