### PR TITLE
Fixes #913

### LINKED ISSUE #913: demo api issue
what am i doing wrong?

```
$ /usr/bin/curl -H 'Accept: application/json' -H 'Content-Type: application/json' \
-H 'X-Cachet-Token: 9yMHsdioQosnyVK4iCVR' \
-d '{ "name": "Unreachable", "status" : 1, "component_id" : 1, "notify" : true }' \
https://demo.cachethq.io/api/v1/incidents

{"errors":[{"id":"30aa4d70-2953-4447-b640-3d5e52701c60","status":400,"title":"Bad Request","detail":"The request cannot be fulfilled due to bad syntax."}]}r
```

### PR DESCRIPTION
**Pull request by jbrooksuk**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Tests failing?

**Comment by jbrooksuk** [comment]
Tests are fixed :)

**Comment by GrahamCampbell** [comment]
Isn't this on the wrong branch?

**Comment by GrahamCampbell** [comment]
This needs to go to 1.2.

**Comment by jbrooksuk** [comment]
1.2 is released?

**Comment by GrahamCampbell** [comment]
Yes, nothing stopping a v1.2.1 though. Depends how far off you think v2.0.0 is?

**Comment by jbrooksuk** [comment]
https://github.com/cachethq/Cachet/issues?q=is%3Aopen+is%3Aissue+milestone%3AV2.0.0

We're almost done. May as well make it 2.0

**Pull request merged**
