### PR TITLE
Remove the remaining use of the lang facade

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by joecohens** [comment]
:+1:

**Comment by joecohens** [comment]
@GrahamCampbell How you move so fast? ;) haha

**Comment by jbrooksuk** [comment]
@joecohens psst, @GrahamCampbell is actually a robot, with rocket engines :rocket:

**Comment by joecohens** [comment]
That's what I thought haha!!

**Comment by GrahamCampbell** [comment]
lol

**Comment by jbrooksuk** [comment]
For what it's worth @GrahamCampbell I'd love to know more about your development process. Do you test? Do you use shortcuts? Automate anything? etc.. Perhaps a blog post some time :)

**Comment by GrahamCampbell** [comment]
I work in sublime text 3, and I normally write tests with phpunit and mockery (not always tdd - cba sometimes), though cachet doesn't have any tests, which does make refactoring more dangerous.

> Do you use shortcuts? Automate anything?

Not really, lol. I recently wrote styleci to automate cs checking though.

**Comment by jbrooksuk** [comment]
You work so quick though! I guess it helps having written Laravel :beers:

**Comment by joecohens** [comment]
@GrahamCampbell Have you tried PHPStorm? It's pretty awesome for structures like this project. Helps you with imports, variable check, and moving between clases pretty quick.

**Comment by GrahamCampbell** [comment]
I have tried phpstorm, but I really like sublime. It's so fast. I really did try with phpstorm, but I just needed to get stuff done, so ended up going back to sublime.

> I guess it helps having written Laravel

That's not exactly true, lol. I may have touched a lot of lines of code in laravel/framework, but most of it was written by taylor.

**Comment by jbrooksuk** [comment]
I tried phpstorm too, but just didn't feel like I was working. Sublime is the bomb. I actually picked up the "Net App of the Year award" back in May for Sublime :)

Heh, well you've got a good understanding of it to say the least.

**Comment by joecohens** [comment]
I guess what @jbrooksuk is that contributing to any project like you do in Laravel gives you kind of an eye for better writing and reading code? @GrahamCampbell your awesome :)

Actually ST it's so fast I some times switch because PHPStorm gets laggy.

**Pull request merged**
