### PR TITLE
Feature/mobile menu

### PR DESCRIPTION
**Pull request by joecohens**
Responsive menu with mobile support.

### CODE REVIEW

**Comment by joecohens** [comment]
For some reason this PR got overwritten so this changes are not on the main branch. Does anybody knows why?

**Comment by joecohens** [comment]
The commits are not in the history, like if it wasn't merged.

**Comment by jbrooksuk** [comment]
Most likely because of me. I've changed Git now though so it'll only ever push the branch I tell it to. Sorry Joe, I'll try fix.

**Comment by jbrooksuk** [comment]
I can't restore the branch :( Do you have it still?

**Comment by joecohens** [comment]
Oh ok ! Don't worry James, I'll fixit I just wanted to know that everything was ok. I don't have the branch but I'll copy and paste it again to make it work :).

**Comment by jbrooksuk** [comment]
I'm really sorry Joe - I've never had issues with Git like this before.

**Comment by joecohens** [comment]
Do not worry at all, what problem did you have?

**Comment by jbrooksuk** [comment]
`push.simple` wasn't set, so every time I did `git push` it was pushing everything and not just my working branch - I believe.

**Comment by joecohens** [comment]
Thats weird.

**Comment by jbrooksuk** [comment]
That, or I did a `git pull` when I should've fetched, then reset my head.

**Comment by joecohens** [comment]
Oooo I know! Are you doing pull explicitly `git pull origin master` or just `git pull``?

**Comment by jbrooksuk** [comment]
Vice-versa.

**Comment by joecohens** [comment]
Some times with only `git pull` you'll get everything up to date even if origin has changes. If you have installed oh my zsh you can do ggpull alias on the current branch so it fetch the origin master only. If I'm not wrong pull does a fetch internally when it knows it's a remote repo.

**Pull request merged**
