### PR TITLE
Webhooks

### PR DESCRIPTION
**Pull request by jbrooksuk**
I've started work on Web Hooks which will allow Cachet to post to other services on updates.

### CODE REVIEW

**Comment by RickB17** [comment]
Does Cachet support using webhooks to create/update incidents?

**Comment by jbrooksuk** [comment]
We actually ended up removing web hooks. They will be making a comeback at some point for some services. In the meantime, you can use the API 😄

**Comment by RickB17** [comment]
Thanks for the quick reply. The API's are working great, I was hoping for easy integration into JIRA via webhooks. I'll look at possibly using Zapier or some other service.

Do you have any recommendations for a solution I could look at that would not require going to an external network to process the webhook request and act as a connector between JIRA and Cachet?

**Comment by jbrooksuk** [comment]
Well, you could look at https://packagist.org/packages/mrbase/cachet-slack-integration and see how @mrbase hooks into the event system. This will require some code changes though.

**Comment by mrbase** [comment]
Yeah, the slack integration is a bit off at the moment tho. The event system changed since I last used it - but feel free :)

**Comment by jbrooksuk** [comment]
v2.4 has a lot more events now 😉

**Pull request merged**
