### PR TITLE
The dashboard API needs to use the Command Bus

### LINKED ISSUE #1927: subscribers receive subscription confirmation email but no followup email when component status changes
### Your setup

- *What version of Cachet?* 2.3
- *What database driver? MySQL? Postgres? SQLite?* MySQL
- *What version of PHP?* 7

### Expected behaviour

In sync mode, I receive an email when I subscribe to notifications on the dashboard to complete my verification. I see a 'Verified' when clicking on the link, so I assume emailing is working as expected.

Later, I try to update the status of a component (from operational to major outage), I expect an email telling me that something is wrong.

### Actual behaviour

I receive no email.

Emails need to be sent from a specific sender so that my smtp server accepts them, this works well for the verification system, but maybe not from the notification system? Could this be checked?

I am not sure if there are any logs of failed emails or anything where I should look. Could you please help me understand what can be happening there?

### PR DESCRIPTION
**Pull request by jbrooksuk**
Fixes #1927

---

The commands are responsible for firing the events, which send the subscribers email.

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Travis is broken. The build is fine. Merging.

**Comment by GrahamCampbell** [comment]
> Travis is broken. The build is fine.

Standard.

**Comment by joecohens** [comment]
👍

**Comment by jbrooksuk** [comment]
In v3.0.0 I want to stop using this bespoke code altogether, everything should run from the API.

**Pull request merged**
