### PR TITLE
Use create instead of createNormalized on handlers

### PR DESCRIPTION
**Pull request by joecohens**
Closes https://github.com/CachetHQ/Cachet/issues/1493

PING @jbrooksuk @GrahamCampbell

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This isn't right?

**Comment by GrahamCampbell** [comment]
That makes this function the same as the normal create one, which means the cases affected by this bug should just be updated to call the correct function, right?

**Comment by GrahamCampbell** [comment]
What I'm saying is that if this behaviour is wanted everywhere, then we need to delete the createNormalized function and everything should be updated to call our create function.

**Comment by joecohens** [comment]
Lol yeah, I didn't realise they where exactly the same. Closing this I'll send another renaming the createNormalized to create where ever it's appropriate

**Comment by GrahamCampbell** [comment]
:)

**Comment by joecohens** [comment]
I'm working on this PR lol

**Comment by GrahamCampbell** [comment]
k ;)

**Comment by GrahamCampbell** [comment]
I'm going to bed now, so won't be able to review this until later tomorrow (potentially not until tomorrow evening depending on how busy tomorrow ends up being, lol).

**Comment by joecohens** [comment]
lol good night Graham ;)

**Comment by jbrooksuk** [comment]
:+1:

**Comment by jbrooksuk** [comment]
Should you also remove the `createNormalized` method too?

**Comment by GrahamCampbell** [comment]
> Should you also remove the createNormalized method too?

If it's unused, yeh.

**Comment by jbrooksuk** [comment]
Actually, we are using it still.

**Pull request merged**
