### PR TITLE
add german translation

### PR DESCRIPTION
**Pull request by Finkregh**
I began a german translation. Might be a bit rough on the edges, so prepare for some more pull-requests :)

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Awesome, thanks @Finkregh! I'll leave this open until you're happy it's all been covered, ok?

**Comment by Finkregh** [comment]
ok, i'll keep you informed ;)

**Comment by jbrooksuk** [comment]
Thanks! Looking forward to merging.

**Comment by jbrooksuk** [comment]
To be honest, it looks like you've covered everything?

**Comment by Finkregh** [comment]
you might want to merge as soon as the last commit has been munched by the bots :smile:

**Comment by jbrooksuk** [comment]
Awesome.

**Pull request merged**
