### PR TITLE
[Proposal] Added background color to sortable list

### PR DESCRIPTION
**Pull request by billmn**
Now sortable list doesn't have a background color and during re-order seems like this:
no-background

I think that with this little change, items are more visible during reorder and can be useful to see "move" cursor on drag-handle hover.

### CODE REVIEW

**Comment by jbrooksuk** [comment]
I don't remember much about this, but is it possible to wrap the dragged item in a border?

**Comment by GrahamCampbell** [comment]
> I don't remember much about this, but is it possible to wrap the dragged item in a border?

:+1:

**Comment by billmn** [comment]
Sure, I'll add it.

Grey background (like sidebar) is ok for you? It can also be white. 

The important thing is that have a background color and not be transparent to increase readability

**Comment by jbrooksuk** [comment]
> Grey background (like sidebar) is ok for you? It can also be white.

Yeah, that's absolutely fine.

**Comment by billmn** [comment]
Done ;)

**Comment by jbrooksuk** [comment]
Sexy. Thanks for this!

**Pull request merged**
