### PR TITLE
Update documentation for PHP builtin server

### PR DESCRIPTION
**Pull request by Crash--**
To run Cachet from the PHP builtin server

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
No, this is a bad idea. Also, the serve artisan command has been removed in laravel 5.

**Comment by Crash--** [comment]
OK if the serve artisan has been removed in laravel 5. 

But I don't see why serving the app from the builtin server is a bad idea! It's a very common usage and it's pretty straightforward to test it...

**Comment by GrahamCampbell** [comment]
I don't think we should encourage it given that it's removed, and running from the cli can give unexpected results, particularly with apcu if people don't configure it correctly.

**Comment by jbrooksuk** [comment]
What you need to know is that when you run `artisan serve` you're not getting a proper web server, only an interface into PHP itself, so it'd be silly to support something that isn't ever properly used.

**Comment by jbrooksuk** [comment]
And, FWIW, I'm able to run `artisan serve` and Cachet works (except for logging in).

**Comment by GrahamCampbell** [comment]
> except for logging in

yeh, probably badly configured apc...

**Comment by Crash--** [comment]
I'm logged within the app, and I can add incidents, etc without any error. (and without APC. I just needed to install apcu - you might add this requirement to your composer.json -). 

I just find that having to install / edit apache or nginx is "pretty complicated". Lot of applications use the builtin server for development or testing purpose (zf, sf...), and I can't imagine that Laravel will remove it at the end. 

With the builtin server, you have a proper web server to develop and to test... without no needed functionalities. 

Anyway, I'm not here to start a war but to contribute. I'll find something else to work on.

**Comment by GrahamCampbell** [comment]
@Crash Yeh, apcu, that was what I was referring to. The driver is called apc.

**Comment by jbrooksuk** [comment]
I'm all for having it in the docs as an unofficial support.

**Comment by GrahamCampbell** [comment]
I don't like it. We'd only have to remove it again in 4 week's time.

**Comment by jbrooksuk** [comment]
Ok :)

**Pull request closed without merging**
