### PR TITLE
Catch invalid model globally on the api

### PR DESCRIPTION
**Pull request by joecohens**
//cc @jbrooksuk @GrahamCampbell Better?

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Looks spot on to me.

**Comment by jbrooksuk** [comment]
Looks Travis is doing that stupid thing again too.

**Comment by jbrooksuk** [comment]
I fixed Travis against the `master`.

**Comment by joecohens** [comment]
Travis sometimes scares me lol

**Pull request merged**
