### PR TITLE
Fix subscribers

### PR DESCRIPTION
**Pull request by joecohens**
/cc @jbrooksuk @GrahamCampbell 

I know we can extract somethings to a mailer but I left them here for now 😛 

screen shot 2016-04-30 at 2 11 53 am

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
BTW, what happens if someone subscribes to something, and then it gets deleted later?

**Comment by joecohens** [comment]
Mmm good question. I think we have to delete the relations by hand

**Comment by GrahamCampbell** [comment]
Do it via events?

**Comment by GrahamCampbell** [comment]
Making a new issue: https://github.com/CachetHQ/Cachet/issues/1739.

**Comment by GrahamCampbell** [comment]
Also https://github.com/CachetHQ/Cachet/issues/1740.

**Comment by jbrooksuk** [comment]
:+1:

**Comment by jbrooksuk** [comment]
🎉

**Pull request merged**
