### PR TITLE
Incident report wasn't sent to subscribers since visible === "1" !== 1

### LINKED ISSUE #745: Incident reports were not sent
Incident reports weren't sent even they're visible and "Notify watchers" is checked

### PR DESCRIPTION
**Pull request by dmitry-textmagic**
Fixes #745 when incident emails weren't sent to subscribers

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Does `master` not work for you with this change https://github.com/cachethq/Cachet/commit/44109dd9fbe93d7da0baba8e42463b15b4e87b6a?

**Comment by dmitry-textmagic** [comment]
My mistake. All works now.

**Comment by jbrooksuk** [comment]
Looks like you may have deployed before I fixed the issue :)

**Comment by dmitry-textmagic** [comment]
Exactly! So fast-paced project, it's great. I will look through changes more careful next time :)

**Comment by jbrooksuk** [comment]
Thanks for your feedback :)

**Pull request closed without merging**
