### PR TITLE
[WIP] Add metrics

### PR DESCRIPTION
**Pull request by joecohens**

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Awesome! I'm going to check this out now.

**Comment by jbrooksuk** [comment]
I know this is a WIP, but couple of things:

1. "Create a metric point" should be something like "Create metric". The metric itself is what the current form does, whereas the point is a measurement of that metric. So you'd add a point to the metric, make sense?
2. Can we show the metric description on the Metrics page?

**Comment by joecohens** [comment]
Sure for both things! I think the "Create a metric point" lang string, was already there before this PR, thanks for spotting it :)

**Comment by jbrooksuk** [comment]
Needs rebasing.

**Comment by jbrooksuk** [comment]
How far off are we on this? :)

**Comment by joecohens** [comment]
I just rebased, pushing. The only thing missing is to set the graph data.

**Comment by jbrooksuk** [comment]
So just the metric points themselves now?

**Comment by jbrooksuk** [comment]
@joecohens can you update the original issue with a task list for what's left?

**Comment by joecohens** [comment]
Moved to https://github.com/cachethq/Cachet/pull/449.

**Pull request closed without merging**
