### PR TITLE
Remove footer icons, make button outline, fix responsive

### PR DESCRIPTION
**Pull request by joecohens**
screen shot 2015-10-26 at 12 10 08 pm
screen shot 2015-10-26 at 12 10 17 pm

Closes https://github.com/cachethq/Cachet/issues/1056

/cc @cachethq/owners

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Ooh, nice!

**Comment by joecohens** [comment]
:beers:

**Comment by jbrooksuk** [comment]
:heart_eyes:

**Comment by GrahamCampbell** [comment]
:heart:

**Comment by TheoBearman** [comment]
Lovely!

**Comment by TheoBearman** [comment]
I think the 'Subscribe' text should not be bold.

**Pull request merged**
