### PR TITLE
Bower has changed the rules in which a name must follow

### PR DESCRIPTION
**Pull request by jbrooksuk**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Needs fixing on 2.3?

**Comment by jbrooksuk** [comment]
Dunno, depends if we need to rebuild assets/

**Comment by GrahamCampbell** [comment]
We will do before the 2.3.0 tag.

**Comment by jbrooksuk** [comment]
Rebase :)

**Comment by GrahamCampbell** [comment]
Cherry-picked into 2.3.

**Pull request closed without merging**
