### PR TITLE
Upgraded to Laravel 5.3

### PR DESCRIPTION
**Pull request by GrahamCampbell**
No idea if this works. ;P

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Ping @jbrooksuk. We are using deprecated routing stuff from 5.2 that got removed in 5.3.

**Comment by jbrooksuk** [comment]
What was it that got removed? I'll finish the upgrades if I can see what's changed :)

**Comment by jbrooksuk** [comment]
Ah. The `controller` method. That's pretty shit lol.

**Comment by jbrooksuk** [comment]
Fixed.

**Comment by jbrooksuk** [comment]
Well, removed the use of `controller` at least... Need to check tests.

**Pull request merged**
