### PR TITLE
Added GrahamCampbell/Core for easier installs

### PR DESCRIPTION
**Pull request by jbrooksuk**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I guess this is fine.

**Comment by jbrooksuk** [comment]
Although... We seed with test data and we don't want that.

**Comment by GrahamCampbell** [comment]
Yeh. We're missusing the seeder there.

**Comment by GrahamCampbell** [comment]
The database seeder shouldn't be used for test data.

**Comment by joecohens** [comment]
We could have a if statement to check if it's a demo env and just in that case run the test data.

**Comment by jbrooksuk** [comment]
We now have a command for Seed :)

**Comment by joecohens** [comment]
:)

**Pull request merged**
