### PR TITLE
Create incident_components table

### PR DESCRIPTION
**Pull request by jbrooksuk**
This creates the `incident_components` table and model. It's not used yet but we'll start to soon.

### CODE REVIEW

**Comment by jbrooksuk** [comment]
@joecohens I'm tempted to add `status_id` for when https://github.com/CachetHQ/Cachet/pull/2643 is done. Would we want to store that data in here rather than on the component itself though?

**Comment by joecohens** [comment]
If we want to "Cache" or potentially have history on the component statuses, it would be cool to have it ;)

**Comment by jbrooksuk** [comment]
A history of statuses would be useful! Yep, will add it before I merge this.

**Comment by jbrooksuk** [comment]
Merging.

**Pull request merged**
