### PR TITLE
Refactored the way incidents are pulled out of the database on the homepage

### PR DESCRIPTION
**Pull request by Lavoaster**
Rather than run a query for _each_ day, this will pull all incidents for the given range out at once and then add the days with no incidents in it.

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Thanks! I've been meaning to do this for a while now :smile:

**Comment by Lavoaster** [comment]
I'll be sending in a PR for this in a few hours. 

The collection needs re-ordering, any days with events will be ordered higher than days without events.

**Comment by jbrooksuk** [comment]
I should revert this commit then?

**Comment by Lavoaster** [comment]
Yeah

**Pull request merged**
