### PR TITLE
[WIP] Move errors to controllers and partial

### PR DESCRIPTION
**Pull request by joecohens**
Closes https://github.com/cachethq/Cachet/issues/343

// cc @cachethq/owners

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Needs a rebase.

**Comment by joecohens** [comment]
Rebased :)

**Comment by jbrooksuk** [comment]
Damn. I should've rewritten the message. Oh well.

**Comment by joecohens** [comment]
:)

**Pull request merged**
