### PR TITLE
Timezone Fixes

### LINKED ISSUE #1072: Remove config() calls from naughty places

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Closes #1072.

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Nice!

**Comment by GrahamCampbell** [comment]
Still failing on HHVM.

**Comment by GrahamCampbell** [comment]
Going to just mark that test as skipped. It's a bug in HHVM, affecting an external library we use, so it's not our fault it's failing.

**Comment by jbrooksuk** [comment]
:+1:

**Comment by joecohens** [comment]
:heart_eyes: I didn't saw this! It's awesome!

**Pull request merged**
