### PR TITLE
Fixed previous and next button dates

### PR DESCRIPTION
**Pull request by farhank3389**

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Can you remove the CSS changes please.

**Comment by jbrooksuk** [comment]
I've just tested it and something weird is going on...

Here are the incidents I have:

```sql
INSERT INTO `incidents` (`id`, `user_id`, `component_id`, `name`, `status`, `visible`, `stickied`, `notifications`, `message`, `occurred_at`, `created_at`, `updated_at`, `deleted_at`)
VALUES
	(1, 1, 0, 'Our monkeys aren\'t performing', 1, 1, 0, 0, 'We\'re investigating an issue with our monkeys not performing as they should be.', '2018-06-17 10:17:50', '2018-06-17 10:17:50', '2018-06-17 10:17:50', NULL),
	(2, 1, 0, 'This is an unresolved incident', 1, 1, 0, 0, 'Unresolved incidents are left without a **Fixed** update.', '2018-06-17 10:17:50', '2018-06-17 10:17:50', '2018-06-17 10:17:50', NULL),
	(3, 1, 0, 'Test', 1, 1, 0, 0, 'Dear customer,\r\n\r\nTest email\r\n\r\nThanks.', '2018-06-11 04:03:19', '2018-06-11 04:03:19', '2018-06-15 04:03:19', NULL);

```

On the index of the status page I can see dates from 18th June - 11th June. In v2.4 the next page link is now the 10th June, on this branch it's the 11th (which is already visible).

What does this fix for you?

**Comment by jbrooksuk** [comment]
Implemented in 335c6f4d500f77c85459ae88b35775d02c218d6f

**Comment by farhank3389** [comment]
Sorry I've been away. Do I need to do anything else? Still relatively new to GitHub so apologies for the confusion

**Comment by jbrooksuk** [comment]
Nope, all good. This should be fixed now, thanks!

**Pull request closed without merging**
