### PR TITLE
fix fatal error 'Undefined variable: component'

### PR DESCRIPTION
**Pull request by gellu**
CachetHQ throws 500 when trying to update component with active subscription

### CODE REVIEW

**Comment by joecohens** [comment]
Thanks! Can you rebase and squash please :)

**Comment by GrahamCampbell** [comment]
@joecohens I've rebased, squashed, and merged this. :)

**Comment by GrahamCampbell** [comment]
Thank you @gellu. :)

**Comment by joecohens** [comment]
👍

**Comment by gellu** [comment]
No problem - happy to contribute. Thanks for awesome service :)

**Comment by jbrooksuk** [comment]
Thanks!

**Pull request merged**
