### PR TITLE
[WIP] Bootstrap v4

### PR DESCRIPTION
**Pull request by jbrooksuk**
@joecohens what do you think about this?

### CODE REVIEW

**Comment by joecohens** [comment]
It seems like a simple change :) is this working ok for you? Shouldn't we wait for a at least a beta version?

**Comment by jbrooksuk** [comment]
Nah, it's nowhere near done yet, I don't think.

**Comment by iamjulians** [comment]
Tested this on a dev build, looked fine and worked fine everywhere I could see 👍

**Comment by jbrooksuk** [comment]
@iamjulians you wouldn't have had the compiled files, so you were only seeing source file changes. If you'd ran `gulp` you'd have seen issues.

**Comment by iamjulians** [comment]
Oh. Makes sense.

**Pull request closed without merging**
