### PR TITLE
Abstract metric class

### PR DESCRIPTION
**Pull request by jbrooksuk**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by GrahamCampbell** [comment]
I already have other things planned here, because reading the config like this is still shite.

**Comment by GrahamCampbell** [comment]
This also conflicts with my config PR.

**Comment by jbrooksuk** [comment]
Ok.

**Comment by GrahamCampbell** [comment]
I want to move stuff into that date class i added, or something simelar.

**Pull request closed without merging**
