### PR TITLE
Add Malay translation

### PR DESCRIPTION
**Pull request by od3n**

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Hey, thanks for your contribution! Unfortunately, we only accept English translations in the GitHub project. Other languages need to be submitted at https://translate.cachethq.io

I hope this is okay?

**Comment by od3n** [comment]
Hi,

Yeah noted.

I requested for Malay on crowdin since last year, yet no feedback.

**Comment by jbrooksuk** [comment]
I'm sorry about that, I've enabled the language now https://translate.cachethq.io/project/cachet/ms#

**Comment by od3n** [comment]
Thanks

**Pull request closed without merging**
