### PR TITLE
Set timezone and date from setup and settings

### PR DESCRIPTION
**Pull request by joecohens**
Closes https://github.com/cachethq/Cachet/issues/281

After this we need a presenter that use the datetime package. The lang thing it's automatic.

### CODE REVIEW

**Comment by joecohens** [comment]
This works also with current installations :)

**Comment by jbrooksuk** [comment]
@joecohens we should implement #192 at the same time as your suggestion.

**Comment by joecohens** [comment]
@jbrooksuk Sure! I like https://github.com/laracasts/Presenter they are really extensible and easy, but I think @GrahamCampbell has also one for auto presenters.

**Comment by GrahamCampbell** [comment]
Yeh, use mine, lol. We actually have 2 maintainers. It's Shawn's pacakge originally. :)

**Comment by joecohens** [comment]
@GrahamCampbell Lol

**Comment by GrahamCampbell** [comment]
Ours support dependency injection into presenters. :P

**Comment by jbrooksuk** [comment]
I need to read about presenters.

**Comment by jbrooksuk** [comment]
So presenters are away of performing logic on a view, before the data goes into the view?

**Comment by joecohens** [comment]
@jbrooksuk Correct.

**Comment by joecohens** [comment]
@GrahamCampbell Just sent a PR to don't use facades since we don't have them registered https://github.com/ShawnMcCool/laravel-auto-presenter/pull/61 help me merge it haha :)

**Comment by jbrooksuk** [comment]
Ok, so an example is that we'd use a Presenter for formatting the timestamps on the incident list?

**Comment by joecohens** [comment]
Yes that would be an example.

**Comment by jbrooksuk** [comment]
Cool! Then yeah, it's absolutely something we should be doing then :)

**Comment by GrahamCampbell** [comment]
I use it for that. NB, we should be using the same api presenters in our api layer instead of duplicating code in transformers.

**Comment by joecohens** [comment]
Definitely!

**Comment by jbrooksuk** [comment]
Makes sense to me. One API format to rule them all.

**Pull request merged**
