### PR TITLE
Make Travis disable xdebug

### PR DESCRIPTION
**Pull request by ConnorVG**
This makes the tests run much quicker as `composer install` is fifty million times faster.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I tried this before and there was zero difference. Let's see what happens this time.

**Comment by ConnorVG** [comment]
mr travis no likey

**Comment by ConnorVG** [comment]
Though the tests were much quicker.

**Comment by ConnorVG** [comment]
I wonder why 7.1 and hhvm don't work: `The command "phpenv config-rm xdebug.ini" failed and exited with 1 during .`

Strange!

**Comment by GrahamCampbell** [comment]
Xdebug doesn't support PHP 7.1 yet, so it's not installed there. :)

**Comment by ConnorVG** [comment]
Still, I didn't really expect it to error just because the config didn't exist. Maybe a warning but not an error. That's fine though, just test _against_ it's version.

**Comment by GrahamCampbell** [comment]
Thx. :P

**Comment by ConnorVG** [comment]
What a savage

image

**Comment by GrahamCampbell** [comment]
Hahaha.

**Pull request merged**
