### PR TITLE
Fix docker manual run instructions

### PR DESCRIPTION
**Pull request by rtrauntvein**
Fixes the Docker manual run instructions to avoid DB migrations issues.

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Can you also suggest edits on our docs page please?

**Comment by GenPage** [comment]
Docs page seems to still be out of date, just a heads up

**Comment by GrahamCampbell** [comment]
Wrong branch.

**Comment by GrahamCampbell** [comment]
Going to have to hard reset to remove it. FFS.

**Comment by GrahamCampbell** [comment]
> Docs page seems to still be out of date, just a heads up

That's because the docs are for 1.1, not 1.2.

**Comment by GrahamCampbell** [comment]
Can you send this PR to 1.2 please.

**Comment by GrahamCampbell** [comment]
1.1 should ONLY be installable by using the docker stuff in THIS repo.

**Pull request merged**
