### PR TITLE
Api groups order

### PR DESCRIPTION
**Pull request by billmn**
Issue: if the request use “?sort=order” returns groups ordered by “order DESC”.

This is unexpected.
If I would a reversed order I have to use “sort=order&order=desc”

### CODE REVIEW

**Comment by jbrooksuk** [comment]
One thing we should add is multiple sorts. Fancy this @billmn?

**Comment by billmn** [comment]
@jbrooksuk Multiple sorts can introduce some BC but I think we can remove the "order" parameter using only "sort":

<code>?sort=-status,order</code> == <code>ORDER BY status DESC, ORDER ASC</code>

**Comment by jbrooksuk** [comment]
I like it, but this breaks BC and I don't like that.

**Comment by ConnorVG** [comment]
I agree with what @jbrooksuk said but I also have a question... What would be the 'default' definition for the sort orders if you're wanting it to go this way? Seems both opinionated _and_ random to me.

**Comment by billmn** [comment]
@jbrooksuk I agree too, nobody loves BC :)

@ConnorVG If I don't specify the "sort" parameter I use a default sorting (eg: for component groups -> status DESC, order ASC).

If I specify the "sort" parameter:
- with the hyphen the order is descending
- without the hyphen the order is ascending

**Comment by ConnorVG** [comment]
I see, I didn't notice the hyphen. Thanks.

**Comment by jbrooksuk** [comment]
I guess we have to break BC on something like this?

**Comment by ConnorVG** [comment]
We don't _have_ to, especially if we use a versioned API.

**Comment by jbrooksuk** [comment]
True. Although that's a ball ache to maintain.

**Comment by ConnorVG** [comment]
:thinking: :thought_balloon:

**Pull request merged**
