### PR TITLE
[WIP] Cachet timezone

### PR DESCRIPTION
**Pull request by joecohens**
/cc @jbrooksuk

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
All 3 of us has commits, lol.

**Comment by joecohens** [comment]
lol

**Comment by jbrooksuk** [comment]
Go team ;)

**Comment by jbrooksuk** [comment]
Everyone happy?

**Comment by billmn** [comment]
:+1:

**Comment by joecohens** [comment]
I should write a quick test for this :)

**Comment by jbrooksuk** [comment]
I should also write the docs.

**Pull request merged**
