### PR TITLE
Fullwidth header

### PR DESCRIPTION
**Pull request by mmollick**
Added support for fullwidth banners/headers.

This includes three new options on the theme settings
* Banner Background Color [default: transparent]
* Banner Padding [default: 40px 0 0 0]
* Enable fullwidth banner? [default: false]

Options:
http://d.pr/i/BwuJ

Fullwidth & background color:
http://d.pr/i/1eZQv

Fixed width & background color
http://d.pr/i/1ewDx

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Nice! @joecohens do you think we're missing anything?

**Comment by joecohens** [comment]
Nice! Looks ok to me :)

**Comment by jbrooksuk** [comment]
Can the logo be vertically centered?

**Comment by mmollick** [comment]
Do you mean contained within the vertical column (as existing banner had it) or vertically centered to the page?

**Comment by mmollick** [comment]
I went ahead and modified to use the existing setup to keep the logo always in the center column.
http://d.pr/i/12bkA

**Comment by jbrooksuk** [comment]
image

This is the issue I have with it.

**Comment by jbrooksuk** [comment]
This is more what I imagined;

image

Ignore the middle alignment.

**Comment by mmollick** [comment]
Ah alright I see what your referring to now, that should actually be controllable by the banner padding option.

**Comment by jbrooksuk** [comment]
Much better, thanks!

**Comment by joecohens** [comment]
:+1:

**Pull request merged**
