### PR TITLE
Removes class authors. Closes #1287

### LINKED ISSUE #1287: Missing or incomplete author information from most classes

### PR DESCRIPTION
**Pull request by jbrooksuk**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Maybe keep them in the tests?

**Comment by GrahamCampbell** [comment]
Since the tests are quite complete.

**Comment by GrahamCampbell** [comment]
I d'no if we should even remove them, lol.

**Comment by jbrooksuk** [comment]
Meh, I'm not fussed either way.

**Comment by GrahamCampbell** [comment]
I think we should just slowly restore the authors.

**Comment by GrahamCampbell** [comment]
Can we make a rule that new code has to at least include correct author data as a starting point?

**Comment by jbrooksuk** [comment]
👍🏻

**Pull request closed without merging**
